### ISSUE TITLE
cannot import name 'runtime_version' from 'google.protobuf' 

### ISSUE THREAD

**Issue by bilibilikanpei** [tensorflow/models#11192]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [x] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the documentation with the issue

https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2.md

## 2. Describe the issue

windows10
python 3.8.6 and 3.9.13

I followed the steps above
An error occurred in this step
`
python object_detection/builders/model_builder_tf2_test.py
`

>PS C:\Users\abc\Desktop\third\models\research> python object_detection/builders/model_builder_tf2_test.py
2024-04-20 15:35:17.379356: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2024-04-20 15:35:17.379541: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "object_detection/builders/model_builder_tf2_test.py", line 24, in <module>
    from object_detection.builders import model_builder
  File "C:\Users\abc\AppData\Local\Programs\Python\Python38\lib\site-packages\object_detection\builders\model_builder.py", line 23, in <module>
    from object_detection.builders import anchor_generator_builder
  File "C:\Users\abc\AppData\Local\Programs\Python\Python38\lib\site-packages\object_detection\builders\anchor_generator_builder.py", line 26, in <module>
    from object_detection.protos import anchor_generator_pb2
  File "C:\Users\abc\AppData\Local\Programs\Python\Python38\lib\site-packages\object_detection\protos\anchor_generator_pb2.py", line 9, in <module>
    from google.protobuf import runtime_version as _runtime_version
ImportError: cannot import name 'runtime_version' from 'google.protobuf' (C:\Users\abc\AppData\Local\Programs\Python\Python38\lib\site-packages\google\protobuf\__init__.py)

so i upgrade protobuf, but

>PS C:\Users\abc\Desktop\third\models\research> pip install --upgrade protobuf
Requirement already satisfied: protobuf in c:\users\abc\appdata\local\programs\python\python38\lib\site-packages (3.19.6)
Collecting protobuf
  Using cached protobuf-5.26.1-cp38-cp38-win_amd64.whl.metadata (592 bytes)
Using cached protobuf-5.26.1-cp38-cp38-win_amd64.whl (420 kB)
Installing collected packages: protobuf
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.19.6
    Uninstalling protobuf-3.19.6:
      Successfully uninstalled protobuf-3.19.6
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
apache-beam 2.46.0 requires protobuf<4,>3.12.2, but you have protobuf 5.26.1 which is incompatible.
google-api-core 2.18.0 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0.dev0,>=3.19.5, but you have protobuf 5.26.1 which is incompatible.
googleapis-common-protos 1.63.0 requires protobuf!=3.20.0,!=3.20.1,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0.dev0,>=3.19.5, but you have protobuf 5.26.1 which is incompatible.
proto-plus 1.23.0 requires protobuf<5.0.0dev,>=3.19.0, but you have protobuf 5.26.1 which is incompatible.
tensorboard 2.10.1 requires protobuf<3.20,>=3.9.2, but you have protobuf 5.26.1 which is incompatible.
tensorflow 2.10.1 requires protobuf<3.20,>=3.9.2, but you have protobuf 5.26.1 which is incompatible.
tensorflow-intel 2.13.0 requires keras<2.14,>=2.13.1, but you have keras 2.10.0 which is incompatible.
tensorflow-intel 2.13.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3, but you have protobuf 5.26.1 which is incompatible.
tensorflow-intel 2.13.0 requires tensorboard<2.14,>=2.13, but you have tensorboard 2.10.1 which is incompatible.
tensorflow-intel 2.13.0 requires tensorflow-estimator<2.14,>=2.13.0, but you have tensorflow-estimator 2.10.0 which is incompatible.
tensorflow-metadata 1.13.0 requires protobuf<4,>=3.13, but you have protobuf 5.26.1 which is incompatible.
Successfully installed protobuf-5.26.1

and retry
>PS C:\Users\abc\Desktop\third\models\research> python object_detection/builders/model_builder_tf2_test.py
2024-04-20 15:39:40.849296: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2024-04-20 15:39:40.849483: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "object_detection/builders/model_builder_tf2_test.py", line 21, in <module>
    import tensorflow.compat.v1 as tf
  File "C:\Users\abc\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\abc\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "C:\Users\abc\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\context.py", line 29, in <module>
    from tensorflow.core.framework import function_pb2
  File "C:\Users\abc\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\core\framework\function_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "C:\Users\abc\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\core\framework\attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "C:\Users\abc\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\core\framework\tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "C:\Users\abc\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\core\framework\resource_handle_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "C:\Users\abc\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\core\framework\tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "C:\Users\abc\AppData\Local\Programs\Python\Python38\lib\site-packages\google\protobuf\descriptor.py", line 621, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
> 1. Downgrade the protobuf package to 3.20.x or lower.
> 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

>More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

how to fix this?

**Comment by bilibilikanpei** [comment]
f*ck, this is a fool issue.
this condition is same with "ImportError: cannot import name 'builder' from 'google.protobuf.internal'".

I've just noticed that packages are not downloaded over the web, but rather parts of the code are generated locally and then built.
By searching globally for problematic import statements, I noticed that they were all on the new green file, so the problem could be in the local generation step.
The highest version of protobuf I initially installed, version 27, worked fine in version 3.18.1 after repeated degradation tests. Finally, you can pass the test

This should be added to note

![image](https://github.com/tensorflow/models/assets/30692234/42cfb68e-2828-40d5-abe2-f344e436bbad)

**Comment by zzanyoung** [comment]
Excuse me, but can you tell me a little more about how you solved it?

**Comment by geoalex91** [comment]
Hi, how did you solve this issue?

**Comment by zzanyoung** [comment]
@geoalex91 [ https://github.com/zzanyoung/EnvNote4GenerateTfrecord ]
This is the environment I set up for learning. It may be helpful for you to refer to it. I installed protobuf version 3.17.0 in a new virtual environment and set the path to Protocol Buffers 22.0.​​​​​​​​​​​​​​​​

**Comment by caoduythanh1997** [comment]
Can you tell me how to solve it?

**Comment by zzanyoung** [comment]
@caoduythanh1997 After installing Protocol Buffer version 22.0, follow the solution with the most votes at the address below.
https://stackoverflow.com/questions/71759248/importerror-cannot-import-name-builder-from-google-protobuf-internal

**Comment by SanjayDurai** [comment]
i tried copy pasting the builder.py but it is not helping for this cannot import name 'runtime_version' from 'google.protobuf' error please can someone help

**Comment by zzanyoung** [comment]
@SanjayDurai Have you tried installing protocol buffer version v22 from the protocolbuffers/protobuf repository?

**Comment by SanjayDurai** [comment]
> @SanjayDurai Have you tried installing protocol buffer version v22 from the protocolbuffers/protobuf repository?

just after after you said but still same error
Traceback (most recent call last):
  File "E:\PROJECTS\SignLanguageDetection\RealTimeObjectDetection\Tensorflow\scripts/generate_tfrecord.py", line 29, in <module>
    from object_detection.utils import dataset_util, label_map_util
  File "C:\Users\SANJAY\.conda\envs\py37\lib\site-packages\object_detection\utils\label_map_util.py", line 29, in <module>
    from object_detection.protos import string_int_label_map_pb2
  File "C:\Users\SANJAY\.conda\envs\py37\lib\site-packages\object_detection\protos\string_int_label_map_pb2.py", line 9, in <module>
    from google.protobuf import runtime_version as _runtime_version
ImportError: cannot import name 'runtime_version' from 'google.protobuf' (C:\Users\SANJAY\.conda\envs\py37\lib\site-packages\google\protobuf\__init__.py)
Traceback (most recent call last):
  File "E:\PROJECTS\SignLanguageDetection\RealTimeObjectDetection\Tensorflow\scripts/generate_tfrecord.py", line 29, in <module>
    from object_detection.utils import dataset_util, label_map_util
  File "C:\Users\SANJAY\.conda\envs\py37\lib\site-packages\object_detection\utils\label_map_util.py", line 29, in <module>
    from object_detection.protos import string_int_label_map_pb2
  File "C:\Users\SANJAY\.conda\envs\py37\lib\site-packages\object_detection\protos\string_int_label_map_pb2.py", line 9, in <module>
    from google.protobuf import runtime_version as _runtime_version
ImportError: cannot import name 'runtime_version' from 'google.protobuf' (C:\Users\SANJAY\.conda\envs\py37\lib\site-packages\google\protobuf\__init__.py)

**Comment by SanjayDurai** [comment]
I'm using [THIS](https://youtu.be/IOI0o3Cxv9Q?si=IbmqPnnIljdXldOn) Video for learning Object detection pls help I'm stuck at create TF records part

**Comment by zzanyoung** [comment]
@SanjayDurai If that's the case, it's possible there might be an issue with the file paths or the input format. Unless you absolutely need to do the conversion locally, I recommend trying out Roboflow.

**Comment by SanjayDurai** [comment]
Thanks Bro ill try it

**Comment by yashruhela821** [comment]
> Thanks Bro ill try it

did it worked?

**Comment by namasSinjali** [comment]
> > @SanjayDurai Have you tried installing protocol buffer version v22 from the protocolbuffers/protobuf repository?
> 
> just tried after you said but still same error Traceback (most recent call last): File "E:\PROJECTS\SignLanguageDetection\RealTimeObjectDetection\Tensorflow\scripts/generate_tfrecord.py", line 29, in from object_detection.utils import dataset_util, label_map_util File "C:\Users\SANJAY.conda\envs\py37\lib\site-packages\object_detection\utils\label_map_util.py", line 29, in from object_detection.protos import string_int_label_map_pb2 File "C:\Users\SANJAY.conda\envs\py37\lib\site-packages\object_detection\protos\string_int_label_map_pb2.py", line 9, in from google.protobuf import runtime_version as _runtime_version ImportError: cannot import name 'runtime_version' from 'google.protobuf' (C:\Users\SANJAY.conda\envs\py37\lib\site-packages\google\protobuf__init__.py) Traceback (most recent call last): File "E:\PROJECTS\SignLanguageDetection\RealTimeObjectDetection\Tensorflow\scripts/generate_tfrecord.py", line 29, in from object_detection.utils import dataset_util, label_map_util File "C:\Users\SANJAY.conda\envs\py37\lib\site-packages\object_detection\utils\label_map_util.py", line 29, in from object_detection.protos import string_int_label_map_pb2 File "C:\Users\SANJAY.conda\envs\py37\lib\site-packages\object_detection\protos\string_int_label_map_pb2.py", line 9, in from google.protobuf import runtime_version as _runtime_version ImportError: cannot import name 'runtime_version' from 'google.protobuf' (C:\Users\SANJAY.conda\envs\py37\lib\site-packages\google\protobuf__init__.py)

If anyone is still confused, the reason this error occurred is because `runtime_version.py` file cannot be found in `C:\Users\SANJAY.conda\envs\py37\lib\site-packages\google\protobuf` directory. The workaround from [this post ](https://stackoverflow.com/questions/71759248/importerror-cannot-import-name-builder-from-google-protobuf-internal) was to:

1. Update protobuf `pip install --upgrade protobuf` which generates the `runtime_version.py`
2. Copy it somewhere else
3. Downgrade back to compatible version `pip install protobuf==3.19.6`. Check compatible version in previous terminal message:
``
Attempting uninstall: protobuf
    Found existing installation: protobuf 3.19.6
    Uninstalling protobuf-3.19.6:
      Successfully uninstalled protobuf-3.19.6
``
4. Downgrade removes the `runtime_version.py` file. Now, copy back the file.

Try running test again `python object_detection/builders/model_builder_tf2_test.py`. In my case I faced the similar issue, this time with `\envs\tensorflow\lib\site-packages\google\protobuf\internal\builder.py`. Just repeat the steps before with `builder.py` file.

**Comment by SanjayDurai** [comment]
ANYBODY OVER HERE COMPLETED THE SIGN LANGUAGE DETETCTION FROM [HERE](https://youtu.be/pDXdlXlaCco?si=2keihIuEaSXnqrRp) OR HAVE GOOD KNOWLEDGE ON OBJECT DETECTION PLS HELP ME  I HAVE COMPLETED THE PROJECT BUT THE MODEL IS ALWAYS DETECTING "YES" AND NOTHING ELSE I TRIED TRAING FOR MORE STEPS BUT STILL ITS DETETCTING ONLY "YES" AND NOT OTHER CLASSES

**Comment by imamhanafi1998** [comment]
> 3\. pip install protobuf==3.19.6

wow this is worked for me. THANKS

**Comment by Ali498609** [comment]
> > > > @SanjayDurai Have you tried installing protocol buffer version v22 from the protocolbuffers/protobuf repository?
> > > 
> > > 
> > > just tried after you said but still same error Traceback (most recent call last): File "E:\PROJECTS\SignLanguageDetection\RealTimeObjectDetection\Tensorflow\scripts/generate_tfrecord.py", line 29, in from object_detection.utils import dataset_util, label_map_util File "C:\Users\SANJAY.conda\envs\py37\lib\site-packages\object_detection\utils\label_map_util.py", line 29, in from object_detection.protos import string_int_label_map_pb2 File "C:\Users\SANJAY.conda\envs\py37\lib\site-packages\object_detection\protos\string_int_label_map_pb2.py", line 9, in from google.protobuf import runtime_version as _runtime_version ImportError: cannot import name 'runtime_version' from 'google.protobuf' (C:\Users\SANJAY.conda\envs\py37\lib\site-packages\google\protobuf__init__.py) Traceback (most recent call last): File "E:\PROJECTS\SignLanguageDetection\RealTimeObjectDetection\Tensorflow\scripts/generate_tfrecord.py", line 29, in from object_detection.utils import dataset_util, label_map_util File "C:\Users\SANJAY.conda\envs\py37\lib\site-packages\object_detection\utils\label_map_util.py", line 29, in from object_detection.protos import string_int_label_map_pb2 File "C:\Users\SANJAY.conda\envs\py37\lib\site-packages\object_detection\protos\string_int_label_map_pb2.py", line 9, in from google.protobuf import runtime_version as _runtime_version ImportError: cannot import name 'runtime_version' from 'google.protobuf' (C:\Users\SANJAY.conda\envs\py37\lib\site-packages\google\protobuf__init__.py)
> > 
> > 
> > If anyone is still confused, the reason this error occurred is because `runtime_version.py` file cannot be found in `C:\Users\SANJAY.conda\envs\py37\lib\site-packages\google\protobuf` directory. The workaround from [this post ](https://stackoverflow.com/questions/71759248/importerror-cannot-import-name-builder-from-google-protobuf-internal) was to:
> > 
> > 1. Update protobuf `pip install --upgrade protobuf` which generates the `runtime_version.py`
> > 2. Copy it somewhere else
> > 3. Downgrade back to compatible version `pip install protobuf==3.19.6`. Check compatible version in previous terminal message:
> >    `Attempting uninstall: protobuf Found existing installation: protobuf 3.19.6 Uninstalling protobuf-3.19.6: Successfully uninstalled protobuf-3.19.6`
> > 4. Downgrade removes the `runtime_version.py` file. Now, copy back the file.
> > 
> > Try running test again `python object_detection/builders/model_builder_tf2_test.py`. In my case I faced the similar issue, this time with `\envs\tensorflow\lib\site-packages\google\protobuf\internal\builder.py`. Just repeat the steps before with `builder.py` file.
> 
> THANKYOU SO MUCH @namasSinjali IT WORKED FINALLY WITHOUT ANY ERRORS

hey bro where is the path of runtime_version.py can you please tell me

**Comment by SanjayDurai** [comment]
> > > > > @SanjayDurai Have you tried installing protocol buffer version v22 from the protocolbuffers/protobuf repository?
> > > > 
> > > > 
> > > > just tried after you said but still same error Traceback (most recent call last): File "E:\PROJECTS\SignLanguageDetection\RealTimeObjectDetection\Tensorflow\scripts/generate_tfrecord.py", line 29, in from object_detection.utils import dataset_util, label_map_util File "C:\Users\SANJAY.conda\envs\py37\lib\site-packages\object_detection\utils\label_map_util.py", line 29, in from object_detection.protos import string_int_label_map_pb2 File "C:\Users\SANJAY.conda\envs\py37\lib\site-packages\object_detection\protos\string_int_label_map_pb2.py", line 9, in from google.protobuf import runtime_version as _runtime_version ImportError: cannot import name 'runtime_version' from 'google.protobuf' (C:\Users\SANJAY.conda\envs\py37\lib\site-packages\google\protobuf__init__.py) Traceback (most recent call last): File "E:\PROJECTS\SignLanguageDetection\RealTimeObjectDetection\Tensorflow\scripts/generate_tfrecord.py", line 29, in from object_detection.utils import dataset_util, label_map_util File "C:\Users\SANJAY.conda\envs\py37\lib\site-packages\object_detection\utils\label_map_util.py", line 29, in from object_detection.protos import string_int_label_map_pb2 File "C:\Users\SANJAY.conda\envs\py37\lib\site-packages\object_detection\protos\string_int_label_map_pb2.py", line 9, in from google.protobuf import runtime_version as _runtime_version ImportError: cannot import name 'runtime_version' from 'google.protobuf' (C:\Users\SANJAY.conda\envs\py37\lib\site-packages\google\protobuf__init__.py)
> > > 
> > > 
> > > If anyone is still confused, the reason this error occurred is because `runtime_version.py` file cannot be found in `C:\Users\SANJAY.conda\envs\py37\lib\site-packages\google\protobuf` directory. The workaround from [this post ](https://stackoverflow.com/questions/71759248/importerror-cannot-import-name-builder-from-google-protobuf-internal) was to:
> > > 
> > > 1. Update protobuf `pip install --upgrade protobuf` which generates the `runtime_version.py`
> > > 2. Copy it somewhere else
> > > 3. Downgrade back to compatible version `pip install protobuf==3.19.6`. Check compatible version in previous terminal message:
> > >    `Attempting uninstall: protobuf Found existing installation: protobuf 3.19.6 Uninstalling protobuf-3.19.6: Successfully uninstalled protobuf-3.19.6`
> > > 4. Downgrade removes the `runtime_version.py` file. Now, copy back the file.
> > > 
> > > Try running test again `python object_detection/builders/model_builder_tf2_test.py`. In my case I faced the similar issue, this time with `\envs\tensorflow\lib\site-packages\google\protobuf\internal\builder.py`. Just repeat the steps before with `builder.py` file.
> > 
> > 
> > THANKYOU SO MUCH @namasSinjali IT WORKED FINALLY WITHOUT ANY ERRORS
> 
> hey bro where is the path of runtime_version.py can you please tell me

.../Lib/site-packages/google/protobuf/internal

**Comment by Ali498609** [comment]
> 3\. pip install protobuf==3.19.6

in my case i couldn't find runtime_version.py file but there is builder.py even if i followed all those steps still i am getting the same error. Can you please tell me how can i resolve that and btw do i need to restart my pc after copying builder.py ?

**Comment by namasSinjali** [comment]
> > 3. pip install protobuf==3.19.6
> 
> in my case i couldn't find runtime_version.py file but there is builder.py even if i followed all those steps still i am getting the same error. Can you please tell me how can i resolve that and btw do i need to restart my pc after copying builder.py ?

You should find the file path information in error message.

**Comment by eversionsystems** [comment]
> > 3. pip install protobuf==3.19.6
> 
> in my case i couldn't find runtime_version.py file but there is builder.py even if i followed all those steps still i am getting the same error. Can you please tell me how can i resolve that and btw do i need to restart my pc after copying builder.py ?

I had to copy a version of runtime_version.py into the path 'Lib\site-packages\google\protobuf' and also remove the error handling within it.

**Comment by AdzanCandra** [comment]
> > > 3. pip install protobuf==3.19.6
> > 
> > 
> > in my case i couldn't find runtime_version.py file but there is builder.py even if i followed all those steps still i am getting the same error. Can you please tell me how can i resolve that and btw do i need to restart my pc after copying builder.py ?
> 
> I had to copy a version of runtime_version.py into the path 'Lib\site-packages\google\protobuf' and also remove the error handling within it.

can you make some tutorial from early until can training the data?

**Comment by vipervenom-debug** [comment]
> > > [@SanjayDurai](https://github.com/SanjayDurai) Have you tried installing protocol buffer version v22 from the protocolbuffers/protobuf repository?
> > 
> > 
> > just tried after you said but still same error Traceback (most recent call last): File "E:\PROJECTS\SignLanguageDetection\RealTimeObjectDetection\Tensorflow\scripts/generate_tfrecord.py", line 29, in from object_detection.utils import dataset_util, label_map_util File "C:\Users\SANJAY.conda\envs\py37\lib\site-packages\object_detection\utils\label_map_util.py", line 29, in from object_detection.protos import string_int_label_map_pb2 File "C:\Users\SANJAY.conda\envs\py37\lib\site-packages\object_detection\protos\string_int_label_map_pb2.py", line 9, in from google.protobuf import runtime_version as _runtime_version ImportError: cannot import name 'runtime_version' from 'google.protobuf' (C:\Users\SANJAY.conda\envs\py37\lib\site-packages\google\protobuf__init__.py) Traceback (most recent call last): File "E:\PROJECTS\SignLanguageDetection\RealTimeObjectDetection\Tensorflow\scripts/generate_tfrecord.py", line 29, in from object_detection.utils import dataset_util, label_map_util File "C:\Users\SANJAY.conda\envs\py37\lib\site-packages\object_detection\utils\label_map_util.py", line 29, in from object_detection.protos import string_int_label_map_pb2 File "C:\Users\SANJAY.conda\envs\py37\lib\site-packages\object_detection\protos\string_int_label_map_pb2.py", line 9, in from google.protobuf import runtime_version as _runtime_version ImportError: cannot import name 'runtime_version' from 'google.protobuf' (C:\Users\SANJAY.conda\envs\py37\lib\site-packages\google\protobuf__init__.py)
> 
> If anyone is still confused, the reason this error occurred is because `runtime_version.py` file cannot be found in `C:\Users\SANJAY.conda\envs\py37\lib\site-packages\google\protobuf` directory. The workaround from [this post ](https://stackoverflow.com/questions/71759248/importerror-cannot-import-name-builder-from-google-protobuf-internal) was to:
> 
> 1. Update protobuf `pip install --upgrade protobuf` which generates the `runtime_version.py`
> 2. Copy it somewhere else
> 3. Downgrade back to compatible version `pip install protobuf==3.19.6`. Check compatible version in previous terminal message:
>    `Attempting uninstall: protobuf Found existing installation: protobuf 3.19.6 Uninstalling protobuf-3.19.6: Successfully uninstalled protobuf-3.19.6`
> 4. Downgrade removes the `runtime_version.py` file. Now, copy back the file.
> 
> Try running test again `python object_detection/builders/model_builder_tf2_test.py`. In my case I faced the similar issue, this time with `\envs\tensorflow\lib\site-packages\google\protobuf\internal\builder.py`. Just repeat the steps before with `builder.py` file.

can you please specify what are you referring here to copy and also tell how to copy it . I am very new to it and dont know how to do it .

**Comment by yywd66** [comment]
> > > [@SanjayDurai](https://github.com/SanjayDurai)你试过从 protocolbuffers/protobuf 仓库安装 protocol buffer 版本 v22 吗？
> > 
> > 
> > 我按照您说的做了，但还是同样的错误。错误信息如下：回溯（最近一次调用）：文件“E:\PROJECTS\SignLanguageDetection\RealTimeObjectDetection\Tensorflow\scripts/generate_tfrecord.py”，第 29 行，在 from object_detection.utils import dataset_util, label_map_util 文件“C:\Users\SANJAY.conda\envs\py37\lib\site-packages\object_detection\utils\label_map_util.py”，第 29 行，在 from object_detection.protos import string_int_label_map_pb2 文件“C:\Users\SANJAY.conda\envs\py37\lib\site-packages\object_detection\protos\string_int_label_map_pb2.py”，第 9 行，在 from google.protobuf import runtime_version as _runtime_version ImportError: 无法从导入名称“runtime_version” 'google.protobuf' (C:\Users\SANJAY\.conda\envs\py37\lib\site-packages\google\protobuf__init_ _.py) 回溯（最近一次调用）： 文件“E:\PROJECTS\SignLanguageDetection\RealTimeObjectDetection\Tensorflow\scripts/generate_tfrecord.py”，第 29 行，在 from object_detection.utils import dataset_util, label_map_util 文件“C:\Users\SANJAY\.conda\envs\py37\lib\site-packages\object_detection\utils\label_map_util.py”，第 29 行，在 from object_detection.protos import string_int_label_map_pb2 文件"C:\Users\SANJAY\.conda\envs\py37\lib\site-packages\object_detection\protos\string_int_label_map_pb2.py", 第 9 行，在 from google.protobuf import runtime_version as _runtime_version ImportError: cannot import name 'runtime_version' from 'google.protobuf' (C:\Users\SANJAY\.conda\envs\py37\lib\site-packages\google\protobuf__init_ _.py)
> 
> 如果还有人不明白，出现此错误的原因是目录`runtime_version.py`中找不到文件。[本文](https://stackoverflow.com/questions/71759248/importerror-cannot-import-name-builder-from-google-protobuf-internal)`C:\Users\SANJAY.conda\envs\py37\lib\site-packages\google\protobuf`提供的解决方法是：[](https://stackoverflow.com/questions/71759248/importerror-cannot-import-name-builder-from-google-protobuf-internal)
> 
> 1. 更新`pip install --upgrade protobuf`生成的protobuf`runtime_version.py`
> 2. 复制到其他地方
> 3. 降级到兼容版本`pip install protobuf==3.19.6`。请在之前的终端消息中查看兼容版本：
>    `Attempting uninstall: protobuf Found existing installation: protobuf 3.19.6 Uninstalling protobuf-3.19.6: Successfully uninstalled protobuf-3.19.6`
> 4. 降级操作会删除该`runtime_version.py`文件。现在，请将该文件复制回来。
> 
> 请尝试再次运行测试`python object_detection/builders/model_builder_tf2_test.py`。我的情况也类似，这次是使用文件时遇到的问题`\envs\tensorflow\lib\site-packages\google\protobuf\internal\builder.py`。只需重复之前的步骤即可`builder.py`。

牛逼啊，直接解决了
