### ISSUE TITLE
Tensorflow error on seq2seq_attention.py line 213 in <module> tf.app.run()

### ISSUE THREAD

**Issue by depiano** [tensorflow/models#1148]
**I'm following the lead for tensorflow (https://github.com/tensorflow/models/tree/master/textsum) and when I make this statement showed the following error:**

**statement:** bazel-bin/textsum/seq2seq_attention \
  --mode=train \
  --article_key=article \
  --abstract_key=abstract \
  --data_path=data/training-* \
  --vocab_path=data/vocab \
  --log_root=textsum/log_root \
  --train_dir=textsum/log_root/train

**Error:**

File "/home/depiano/Scrivania/TextSummarization/bazel-bin/textsum/seq2seq_attention.runfiles/__main__/textsum/seq2seq_attention.py", line 213, in <module>
    tf.app.run()
  File "/home/depiano/Scrivania/Virtualenv/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/depiano/Scrivania/TextSummarization/bazel-bin/textsum/seq2seq_attention.runfiles/__main__/textsum/seq2seq_attention.py", line 196, in main
    _Train(model, batcher)
  File "/home/depiano/Scrivania/TextSummarization/bazel-bin/textsum/seq2seq_attention.runfiles/__main__/textsum/seq2seq_attention.py", line 85, in _Train
    model.build_graph()
  File "/home/depiano/Scrivania/TextSummarization/textsum/seq2seq_attention_model.py", line 295, in build_graph
    self._add_seq2seq()
  File "/home/depiano/Scrivania/TextSummarization/textsum/seq2seq_attention_model.py", line 142, in _add_seq2seq
    encoder_inputs = tf.unpack(tf.transpose(self._articles))
AttributeError: 'module' object has no attribute 'unpack'
Errore di segmentazione (core dump creato)

**Comment by prb12** [comment]
You have not provided details of your TensorFlow version and operating system etc., which makes it easier to triage problems like this.

Superficially this appears to be code which has not been updated for TensorFlow 1.0 APIs.  Please see https://www.tensorflow.org/install/migration
 
@panyx0718 and @peterjliu can comment further.

**Comment by depiano** [comment]
I'm use Tensorflow v.1.0.1 on Ubuntu 16.04LTS.
I followed your steps, but I have not solved.
I hope someone can help me, are several days that I can not solve

**Comment by xtr33me** [comment]
@depiano It seems that this model has not been updated for TF 1.0.  I was going to take a stab at exporting this model again and after updating TF, I received the same issue.  After further research it looks as though **tf.unpack** has been renamed to **tf.unstack**.  Unfortunately it seems that I received another error related to no attribute 'rnn_cell', so the above fix will fix your current issue but probably not all of them.  It looks as if this model just needs some slight updating to be in-line with the most recent TF. If you want to get some working quickly, I'd recommend just using 0.11 or 0.12 for now.  However I am going to trek down this project and see if I can get it working with 1.0.

The below ticket was where I saw the above resolution.
https://github.com/fchollet/keras/issues/5226

**Comment by depiano** [comment]
I installed version 0.12 tensorflow and I have not the first error. But now displaying the following warning and prompt stops asking input.
Why ?

**Warning:** 
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/logging_ops.py:264 in merge_all_summaries.: merge_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.merge.
WARNING:tensorflow:From /home/depiano/Scrivania/TextSummarization/bazel-bin/textsum/seq2seq_attention.runfiles/__main__/textsum/seq2seq_attention.py:122 in _Eval.: __init__ (from tensorflow.python.training.summary_io) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.FileWriter. The interface and behavior is the same; this is just a rename.

Thank you!

**Comment by xtr33me** [comment]
Think this can be closed as stated above this is just a rename.
