### ISSUE TITLE
vid2depth dose not work with Tensorflow 2.4

### ISSUE THREAD

**Issue by krcc5978** [tensorflow/models#9628]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x] I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/research/vid2depth

## 2. Describe the bug

I used vid2depth with tensorflow2.4 and I got the following error.

I thought tensorflow2.4 removed contrib.

```
(poc_env) (my PC path)\models\research\vid2depth>python inference.py --kitti_dir ./kitti-raw-uncompressed --output_dir ./inference --kitti_video 2011_09_26/2011_09_26_drive_0009_sync --model_ckpt ./trained-model/model-119496
2021-01-13 14:55:26.735626: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
Traceback (most recent call last):
  File "inference.py", line 44, in <module>
    import model
  File "(my PC path)\models\research\vid2depth\model.py", line 23, in <module>
    import nets
  File "(my PC path)\models\research\vid2depth\nets.py", line 27, in <module>
    slim = tf.contrib.slim
AttributeError: module 'tensorflow' has no attribute 'contrib'
```

## 3. Steps to reproduce

Steps to reproduce the behavior.

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow version (use command below): Tensorflow-gpu 2.4
- Python version: python 3.7
- CUDA/cuDNN version: CUDA 11
- GPU model and memory: Geforce RTX 3090

**Comment by saberkun** [comment]
AttributeError: module 'tensorflow' has no attribute 'contrib'
This indicates the code only works for TF 1.15.
In the readme, we have added a badge indicating it does not run with TF 2.x.
The model is from researchers so they may not update the code.

**Comment by krcc5978** [comment]
@saberkun 

Thank you for reply!!
I thought vid2depth would work with tensorflow2.4 when I read this README(https://github.com/tensorflow/models/blob/master/README.md)  
I hope this is updated!!
