### ISSUE TITLE
Receive 'module' object has no attribute 'rnn_cell' when running translate model

### ISSUE THREAD

**Issue by aronayne** [tensorflow/models#919]
tensorflow version 0.12.head
Python version : 2.7.6 :

Attempting to run https://github.com/tensorflow/models/tree/master/tutorials/rnn/translate I receive : 

File "/notebooks/models/tutorials/rnn/translate/seq2seq_model.py", line 117, in init
single_cell = tf.nn.rnn_cell.GRUCell(size)
AttributeError: 'module' object has no attribute 'rnn_cell'

Received this while running translate model : https://github.com/tensorflow/models/tree/master/tutorials/rnn/translate

This also recreates the error : 

import tensorflow as tf
print(tf.nn.rnn_cell.BasicRNNCell)
returns :

import tensorflow as tf
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcurand.so.8.0 locally
print(tf.nn.rnn_cell.BasicRNNCell)
Traceback (most recent call last):
File "", line 1, in 
AttributeError: 'module' object has no attribute 'rnn_cell'

This issue appears related to https://github.com/zsdonghao/tensorlayer/issues/48
Suggested fix is to update to latest tensorflow version. I receive this error on head : 0.12.head

This issue has not been resolved ?

**Comment by asimshankar** [comment]
The tutorial is setup to work with the latest release (0.12.1) and not necessarily the head of the source tree (0.12.head).

We're currently making some API changes in preparation for a 1.0 release, after which the API should be much more stable.  For example, `GRUCell` is in `tf.contrib.rnn.GRUCell`.

@nealwu @lukaszkaiser @xiejw : Is this tutorial supposed to be updated?

**Comment by xiejw** [comment]
@ebrevdo +ebrevdo here.

**Comment by ebrevdo** [comment]
What asim said 😊

**Comment by asimshankar** [comment]
Closing this out since the model is working with the latest stable release.

**Comment by jsmlay** [comment]
I run into the same error on windows 7, with tf version 1.0.0-alpha

Python 3.5.3rc1 (v3.5.3rc1:de530d7f21c0, Jan  2 2017, 06:41:25) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> print(tf.nn.rnn_cell.BasicRNNCell)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'tensorflow.python.ops.nn' has no attribute 'rnn_cell'
>>> print(tf.__version__)
1.0.0-alpha
>>>

**Comment by Graystripe17** [comment]
@asimshankar I have tensorflow 1.0.0 and this error shows up.

**Comment by ebrevdo** [comment]
The RNNCells have been temporarily moved to tf.contrib.rnn
(tf.contrib.rnn.BasicRNNCell).  They will hopefully be moved back out of
contrib starting in TensorFlow 1.1.

**Comment by derdav3** [comment]
`tf.contrib.rnn.BasicRNNCell` is reachable but `tf.contrib.rnn.NASCell` throws the `'module' object has no attribute 'NASCell'` error... where is NASCell? :)

**Comment by nealwu** [comment]
@derdav3 It looks like [NASCell](https://www.tensorflow.org/versions/r1.1/api_docs/python/tf/contrib/rnn/NASCell) is only available starting in TensorFlow 1.1. You should [install TensorFlow from source](https://www.tensorflow.org/install/install_sources).

**Comment by ebrevdo** [comment]
You can also download a TensorFlow nightly:

https://github.com/tensorflow/tensorflow#installation

**Comment by nealwu** [comment]
@batlogs You want [`tf.contrib.rnn.GRUCell`](https://www.tensorflow.org/api_docs/python/tf/contrib/rnn/GRUCell). In the future you can also just search the TensorFlow documentation to see if it solves your issue.
