### ISSUE TITLE
when I run"python object_detection/model_main.py --pipeline_config_path=xxx/models-master/traindata/data/ssd_mobilenet_v2_pets_keras.config --model_dir=training --num_train_steps=60000 --num_eval_steps=20 --alsologtostderr",ERROR:File "/usr/local/lib/python3.5/dist-packages/object_detection-0.1-py3.5.egg/object_detection/utils/tf_version.py", line 17, in <module>     from tensorflow.python import tf2  # pylint: disable=import-outside-toplevel ImportError: cannot import name 'tf2'

### ISSUE THREAD

**Issue by HYG-777** [tensorflow/models#8551]
tf2?it is tf1.12,is 1.15 nessary?

**Comment by HYG-777** [comment]
python object_detection/builders/model_builder_test.py
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 21, in <module>
    from object_detection.builders import model_builder
  File "/home/shen/hyg/TFslimAPI/models-master/research/object_detection/builders/model_builder.py", line 39, in <module>
    from object_detection.utils import tf_version
  File "/home/shen/hyg/TFslimAPI/models-master/research/object_detection/utils/tf_version.py", line 17, in <module>
    from tensorflow.python import tf2  # pylint: disable=import-outside-toplevel
ImportError: cannot import name 'tf2'

**Comment by sohartma** [comment]
I'm having the same issue! 
from object_detection.utils import tf_version File "/root/.local/lib/python2.7/site-packages/object_detection/utils/tf_version.py", line 17, in <module> from tensorflow.python import tf2 # pylint: disable=import-outside-toplevel ImportError: cannot import name tf2

**Comment by Lotfi-MERAD** [comment]
I have the same issue :( , any solution please ?( i haven't any problem with 1.15 version ,but when i try 1.8 version of tensorflow give me the same issue !!!!

**Comment by sohartma** [comment]
> 
> 
> I have the same issue :( , any solution please ?( i haven't any problem with 1.15 version ,but when i try 1.8 version of tensorflow give me the same issue !!!!

think it only works with 1.15... I had tensorflow 1.14 installed and got this error, I'm trying it again today with 1.15

**Comment by HYG-777** [comment]
> I have the same issue :( , any solution please ?( i haven't any problem with 1.15 version ,but when i try 1.8 version of tensorflow give me the same issue !!!!

just try tf2, When I used the previously downloaded version, it worked(tf 1.5 and download monthes ago)
