### PR TITLE
Keras-fy NCF Model

### PR DESCRIPTION
**Pull request by seemuch**
Made a keras implementation of the NCF model. Extract some common code used by both Keras and Estimator into the ncf_common.py file. 

The command I used to run the keras code:
```
python ncf_keras_main.py \
--model_dir "/tmp/model_dir/ncf/" \
--data_dir "/data/movielens_data" \
--dataset "ml-20m" \
--hooks "" \
--num_gpus 1 \
--clean \
--train_epochs 14 \
--batch_size 160000 \
--learning_rate 0.00382059 \
--beta1 0.783529 \
--beta2 0.909003 \
--epsilon 1.45439e-07 \
--layers 256,256,128,64 \
--num_factors 64 \
--hr_threshold 0.635 \
--ml_perf
```

Todo:
1. TPU support. (Not necessarily in this PR or by me)
2. Distribution strategy support. 

Update: the model does not converge with DS, and I have not been able to find out why. 
This PR is going to focus on non-DS versino.

### CODE REVIEW

**Comment by tfboyd** [comment]
Nice I will try to give this a try as we review.

**Comment by robieta** [comment]
Note: @reedwm is optional

**Comment by robieta** [comment]
I don't understand why you pulled the metric computation out of neumf.py into ncf_common.

Also, can you use `git mv` to minimize the diffs?

**Comment by seemuch** [comment]
Re robieta: the reason I pulled the metrics computation to ncf_common was because this file contains the code that is used by both keras and estimator implementations. 
About git mv, I think I am a little rusty with git. The code in ncf_common mainly comes from two files: ncf_main.py and neumf_model.py. How should I use git mv to achieve better diffs, please?

**Comment by robieta** [comment]
I would still say that the code should be left in neumf.py. We went through a similar procedure with some of Shawn's low level runners, and what wound up making sense is to break things into functions and then have individual consumers of the topology grab whatever level of granularity of functions that they need.

Re. `git mv`, the code would look something like:
```
git diff --stat master -- .
mv ncf_main.py ncf_estimator_main.py
mv ncf_common.py ncf_main.py
git add .
git commit -m "move pt 1"

git mv ncf_main.py ncf_common.py
git commit -m "move pt 2"
git diff --stat master -- .
git diff master -- .
```
(It doesn't appear to be possible to reuse the name ncf_main without confusing git.) This plus moving stuff back to neumf.py brings the diff down to about +500 -200.

File: official/recommendation/ncf_keras_main.py [hunk 1]
```diff
@@ -0,0 +1,204 @@
...
+def run_ncf(_):
+  """Run NCF training and eval with Keras."""
+  params = ncf_common.parse_flags(FLAGS)
+  batch_size = params['batch_size']
+
+  num_users, \
+      num_items, \
+      num_train_steps, \
+      num_eval_steps, \
+      producer = ncf_common.get_inputs(params)
```
[the remark this answers is not in the document]
Comment (seemuch) [reply official/recommendation/ncf_keras_main.py]: Yes. Changed. Thanks!

File: official/recommendation/ncf_keras_main.py [hunk 2]
```diff
@@ -0,0 +1,204 @@
...
+      shape=(), batch_size=batch_size, name=rconst.VALID_POINT_MASK, dtype=tf.int32)
+
+  base_model = neumf_model.construct_model(user_input, item_input, params)
+  keras_model_input = base_model.input
+
+  keras_model_input.append(dup_mask_input)
+  keras_model_input.append(labels_input)
+  keras_model_input.append(valid_pt_mask_input)
+
+  keras_model = tf.keras.Model(
```
[the remark this answers is not in the document]
Comment (seemuch) [reply official/recommendation/ncf_keras_main.py]: My understanding is that the keras_model is built based on base_model. 
Even if the attributes of base_model is changed, it does not matter. All it is used is to build the keras_model. 
The `input` and `inputs` in this case are equivalent. I verified.

File: official/recommendation/ncf_keras_main.py [hunk 3]
```diff
@@ -0,0 +1,204 @@
...
+      inputs=keras_model_input,
+      outputs=base_model.output)
+  keras_model.summary()
+
+  def pre_process_training_input(features, labels):
+    # Add a dummy dup_mask to the input dataset
```
[the remark this answers is not in the document]
Comment (seemuch) [reply official/recommendation/ncf_keras_main.py]: Done.

File: official/recommendation/ncf_keras_main.py [hunk 4]
```diff
@@ -0,0 +1,204 @@
...
+      labels=labels_input,
+      logits=softmax_logits,
+      weights=tf.cast(valid_pt_mask_input, tf.float32),
+  )
+  loss_tensor= tf.identity(loss_tensor, name="train_loss")
+  keras_model.add_loss(loss_tensor)
+
+  # Custom loss function for the hit rate
+  logits = keras_model.output
+  softmax_logits = ncf_common.softmax_logitfy(logits)
```
[the remark this answers is not in the document]
Comment (seemuch) [reply official/recommendation/ncf_keras_main.py]: Done.

File: official/recommendation/ncf_keras_main.py [hunk 5]
```diff
@@ -0,0 +1,204 @@
...
+
+  cross_entropy, \
+  metric_fn, \
+  in_top_k, \
+  ndcg, \
+  metric_weights = ncf_common.compute_eval_loss_and_metrics_helper(
```
[the remark this answers is not in the document]
Comment (seemuch) [reply official/recommendation/ncf_keras_main.py]: Fixed.

File: official/recommendation/ncf_keras_main.py [hunk 6]
```diff
@@ -0,0 +1,204 @@
...
+      logits,
+      softmax_logits,
+      tf.cast(dup_mask_input, tf.float32),
+      params["num_neg"],
+      params["match_mlperf"],
+      use_tpu_spec=params["use_xla_for_gpu"])
+
+  values = in_top_k
```
[the remark this answers is not in the document]
Comment (seemuch) [reply official/recommendation/ncf_keras_main.py]: Done.

File: official/recommendation/ncf_keras_main.py [hunk 7]
```diff
@@ -0,0 +1,204 @@
...
+
+  values = tf.cond(
+      tf.keras.backend.learning_phase(),
+      lambda: tf.zeros(shape=in_top_k.shape, dtype=in_top_k.dtype),
+      lambda: values)
+  values = tf.identity(values, "hit_rate")
```
[the remark this answers is not in the document]
Comment (seemuch) [reply official/recommendation/ncf_keras_main.py]: Done.

File: official/recommendation/ncf_keras_main.py [hunk 8]
```diff
@@ -0,0 +1,204 @@
...
+  dup_mask_input = tf.keras.layers.Input(
+      shape=(), batch_size=batch_size, name=rconst.DUPLICATE_MASK, dtype=tf.int32)
+  # Labels as input for the custom loss function
+  labels_input = tf.keras.layers.Input(
+      shape=(), batch_size=batch_size, name="labels", dtype=tf.int32)
+  # valid_point_mask as input for the custom loss function
+  valid_pt_mask_input = tf.keras.layers.Input(
+      shape=(), batch_size=batch_size, name=rconst.VALID_POINT_MASK, dtype=tf.int32)
+
+  base_model = neumf_model.construct_model(user_input, item_input, params)
```
[the remark this answers is not in the document]
Comment (seemuch) [reply official/recommendation/ncf_keras_main.py]: Done.

File: official/recommendation/ncf_keras_main.py [hunk 9]
```diff
@@ -0,0 +1,204 @@
...
+
+  keras_model.fit(train_input_dataset,
+      epochs=FLAGS.train_epochs,
+      steps_per_epoch=num_train_steps,
+      callbacks=[IncrementEpochCallback(producer)],
+      verbose=2)
+
+  tf.logging.info("Training done. Start evaluating")
+
+  def pre_process_eval_input(features):
```
[the remark this answers is not in the document]
Comment (seemuch) [reply official/recommendation/ncf_keras_main.py]: Done.

File: official/recommendation/ncf_common.py [hunk 10]
```diff
@@ -0,0 +1,501 @@
...
+    num_training_neg: The number of negatives per positive during training.
+
+    match_mlperf: Use the MLPerf reference convention for computing rank.
+
+    use_tpu_spec: Should a TPUEstimatorSpec be returned instead of an
+      EstimatorSpec. Required for TPUs and if XLA is done on a GPU. Despite its
+      name, TPUEstimatorSpecs work with GPUs
+
+  Returns:
+    An EstimatorSpec for evaluation.
```
[the remark this answers is not in the document]
Comment (seemuch) [reply official/recommendation/ncf_common.py]: Done. 
Moved back to neumf_model.py

File: official/recommendation/ncf_keras_main.py [hunk 11]
```diff
@@ -0,0 +1,204 @@
...
+      tf.cast(dup_mask_input, tf.float32),
+      params["num_neg"],
+      params["match_mlperf"],
+      use_tpu_spec=params["use_xla_for_gpu"])
+
+  values = in_top_k
+
+  values = tf.cond(
+      tf.keras.backend.learning_phase(),
+      lambda: tf.zeros(shape=in_top_k.shape, dtype=in_top_k.dtype),
```
[the remark this answers is not in the document]
Comment (seemuch) [reply official/recommendation/ncf_keras_main.py]: Yes.

File: official/recommendation/ncf_common.py [hunk 12]
```diff
@@ -0,0 +1,501 @@
...
+
+  xla_message = "--use_xla_for_gpu is incompatible with --tpu"
+  @flags.multi_flags_validator(["use_xla_for_gpu", "tpu"], message=xla_message)
+  def xla_validator(flag_dict):
+    return not flag_dict["use_xla_for_gpu"] or not flag_dict["tpu"]
+
+
+def softmax_logitfy(logits):
+  '''Convert the logits returned by the base model to softmax logits.'''
+  softmax_logits = tf.concat([logits * 0, logits], axis=1)
```
[the remark this answers is not in the document]
Comment (robieta) [reply official/recommendation/ncf_common.py]: Including why this is necessary would be good. Also please change the name to something like `convert_to_softmax_logits`.

File: official/recommendation/ncf_keras_main.py [hunk 13]
```diff
@@ -0,0 +1,241 @@
...
+  softmax_logits = ncf_common.convert_to_softmax_logits(logits)
+
+  _add_custom_loss(
+      keras_model,
+      logits,
+      softmax_logits,
+      labels_input,
+      tf.cast(valid_pt_mask_input, tf.float32))
+
+  _add_custom_metric(
```
Comment (fchollet) [inline official/recommendation/ncf_keras_main.py]: Also this would be more readable if structured as

metric = _get_custom_metric(logits, mask, ...)
model.add_metric(metric)

File: official/recommendation/ncf_keras_main.py [hunk 14]
```diff
@@ -0,0 +1,241 @@
...
+  num_users, num_items, num_train_steps, num_eval_steps, producer = (
+      ncf_common.get_inputs(params))
+
+  params["num_users"], params["num_items"] = num_users, num_items
+  producer.start()
+  model_helpers.apply_clean(flags.FLAGS)
+
+  # TODO(shiningsun): Both MirroredStrategy and OneDeviceStrategy error out.
+  # Find out why and change the distribute to distribution
+  with distribution_utils.MaybeDistributionScope(None):
```
Comment (fchollet) [inline official/recommendation/ncf_keras_main.py]: Would be good to document what this does

File: official/recommendation/ncf_keras_main.py [hunk 15]
```diff
@@ -0,0 +1,241 @@
...
+    keras_model = _get_keras_model(params)
```
Comment (fchollet) [inline official/recommendation/ncf_keras_main.py]: Would be good to use explicit keyword args instead of "params" to improve readability

File: official/recommendation/ncf_keras_main.py [hunk 16]
```diff
@@ -0,0 +1,241 @@
...
+
+    optimizer = ncf_common.get_optimizer(params)
```
Comment (fchollet) [inline official/recommendation/ncf_keras_main.py]: Same

File: official/recommendation/ncf_keras_main.py [hunk 17]
```diff
@@ -0,0 +1,241 @@
...
+    keras_model.compile(optimizer=optimizer)
+
+    train_input_dataset, eval_input_dataset = _get_train_and_eval_data(producer, params)
```
Comment (fchollet) [inline official/recommendation/ncf_keras_main.py]: Same, you would have better readability with explicit args

File: official/recommendation/ncf_keras_main.py [hunk 18]
```diff
@@ -0,0 +1,241 @@
...
+        eval_input_dataset,
+        steps=num_eval_steps,
+        verbose=2)
+
+    tf.logging.info("Keras evaluation is done.")
+
+  return eval_results
+
+
+def _get_keras_model(params):
```
Comment (fchollet) [inline official/recommendation/ncf_keras_main.py]: Explicit args for `params`, plus a docstring documenting them, would be great

File: official/recommendation/ncf_keras_main.py [hunk 19]
```diff
@@ -0,0 +1,241 @@
...
+
+  keras_model = tf.keras.Model(
+      inputs=keras_model_inputs,
+      outputs=base_model.outputs)
+  keras_model.summary()
+
+  logits = keras_model.output
+  softmax_logits = ncf_common.convert_to_softmax_logits(logits)
+
+  _add_custom_loss(
```
[the remark this answers is not in the document]
Comment (seemuch) [reply official/recommendation/ncf_keras_main.py]: Done.

File: official/recommendation/ncf_keras_main.py [hunk 20]
```diff
@@ -0,0 +1,241 @@
...
+
+    optimizer = ncf_common.get_optimizer(params)
+    keras_model.compile(optimizer=optimizer)
+
+    train_input_dataset, eval_input_dataset = _get_train_and_eval_data(producer, params)
+
+    keras_model.fit(train_input_dataset,
+        epochs=FLAGS.train_epochs,
+        steps_per_epoch=num_train_steps,
+        callbacks=[IncrementEpochCallback(producer)],
```
[the remark this answers is not in the document]
Comment (seemuch) [reply official/recommendation/ncf_keras_main.py]: I think I discussed this with Taylor, and it cannot be easily achieved. 
The producer is putting stuff into the queue, it only maintains the left side of the sliding window. Here I am trying to move the other side of the sliding window. I don't think producer is able to do this.

File: official/recommendation/ncf_keras_main.py (hunk 13 above)
Comment (seemuch) [reply official/recommendation/ncf_keras_main.py]: Done.

File: official/recommendation/ncf_keras_main.py (hunk 14 above)
Comment (seemuch) [reply official/recommendation/ncf_keras_main.py]: This is the new distribution strategy API. Instead of passing the distribution strategy object to the `compile()`, we should use this scope thing.

File: official/recommendation/ncf_keras_main.py (hunk 20 above)
[the remark this answers is not in the document]
Comment (robieta) [reply official/recommendation/ncf_keras_main.py]: To provide some context on why this is the way it is (and how we might be able to make it cleaner):

There are two paths for getting data from the data generation thread to the training process. The GPU case is easy because it it all local, so the generation thread simply puts data onto a queue while the main thread pulls data off that queue using a generator and `tf.data.Dataset.from_generator`.  So in that case you could absolutely increment the count when the generator finished yielding before returning. (Which I think is what you're getting at.)

However in the TPU case, the data generation thread writes the data to TFRecord files, and the contents of those files is streamed to the TPU via `StreamingFilesDataset`. In that case there is no Python inside the `Dataset`, and it therefore cannot increment the counter. So in order to keep the behavior consistent I made the count increment happen in the run loop code rather than the Dataset. (And the Callback is the analog of that decision.)

Luckily it turns out `StreamingFilesDataset` is more flexible than I had realized (thanks to @saeta for pointing this out!) and can stream the results of a `Dataset` running locally, effectively eliminating the need for the manual sharding/serialization/deserialization code that is currently in the TPU path. With that pattern, both GPU and TPU paths would start from the same `tf.data.Dataset.from_generator` and your intuition about not needing the Callback is correct. @tayo is currently looking at the TPU side of NCF.

So to make a long story short, that Callback can (and should) go away soon, but not quite yet. Hope that helps.

[the remark this answers is not in the document]
Comment (seemuch) [reply official/recommendation/ncf_keras_main.py]: Thanks for the explanation.

[the remark this answers is not in the document]
Comment (tayo) [reply official/recommendation/ncf_keras_main.py]: @seemuch I am indeed working on the TPU path.  
@robieta Thanks for pointing out the StreamingFilesDataset simplification

File: official/recommendation/run.sh [hunk 21]
```diff
@@ -58,7 +58,7 @@ do
   # To reduce variation set the seed flag:
   #   --seed ${i}
 
-  python -u "${SCRIPT_DIR}/ncf_main.py" \
+  python -u "${SCRIPT_DIR}/ncf_estimator_main.py" \
```
Comment (robieta) [inline official/recommendation/run.sh]: It might make sense to have a thin shim run_keras.sh that for the most part uses run.sh, (similar to how run_tpu.sh works) That way it's very easy to reproduce issues.

File: official/recommendation/ncf_estimator_main.py [hunk 22]
```diff
@@ -0,0 +1,197 @@
...
+  mlperf_helper.ncf_print(key=mlperf_helper.TAGS.RUN_STOP,
+                          value={"success": target_reached})
+  producer.stop_loop()
+  producer.join()
+
+  # Clear the session explicitly to avoid session delete error
+  tf.keras.backend.clear_session()
+
+  mlperf_helper.ncf_print(key=mlperf_helper.TAGS.RUN_FINAL)
+
```
[the remark this answers is not in the document]
Comment (seemuch) [reply official/recommendation/ncf_estimator_main.py]: Done.

File: official/recommendation/ncf_keras_main.py [hunk 23]
```diff
@@ -0,0 +1,218 @@
...
+from official.utils.logs import logger
+from official.utils.logs import mlperf_helper
+from official.utils.misc import model_helpers
+
+
+FLAGS = flags.FLAGS
+
+
+def _keras_loss(y_true, y_pred):
+  loss = tf.losses.sparse_softmax_cross_entropy(
```
[the remark this answers is not in the document]
Comment (seemuch) [reply official/recommendation/ncf_keras_main.py]: Done.

File: official/recommendation/ncf_keras_main.py [hunk 24]
```diff
@@ -0,0 +1,218 @@
...
+        softmax_logits,
+        dup_mask,
+        params["num_neg"],
+        params["match_mlperf"],
+        params["use_xla_for_gpu"])
+
+  return metric_fn
+
+
+def _get_hit_rate_metric(
```
[the remark this answers is not in the document]
Comment (seemuch) [reply official/recommendation/ncf_keras_main.py]: Done.

File: official/recommendation/ncf_keras_main.py [hunk 25]
```diff
@@ -0,0 +1,218 @@
...
+
+def _get_keras_model(params):
+  """Constructs and returns the model."""
+  batch_size = params['batch_size']
+
+  user_input = tf.keras.layers.Input(
+      shape=(),
+      batch_size=batch_size,
+      name=movielens.USER_COLUMN,
+      dtype=tf.int32)
```
[the remark this answers is not in the document]
Comment (seemuch) [reply official/recommendation/ncf_keras_main.py]: Done.

File: official/recommendation/ncf_common.py [hunk 26]
```diff
@@ -174,112 +105,60 @@ def parse_flags(flags_obj):
...
-        cycle_index + 1, total_training_cycle))
-
-    mlperf_helper.ncf_print(key=mlperf_helper.TAGS.TRAIN_EPOCH,
-                            value=cycle_index)
-
-    train_input_fn = producer.make_input_fn(is_training=True)
-    estimator.train(input_fn=train_input_fn, hooks=train_hooks,
-                    steps=num_train_steps)
+def get_optimizer(params):
+  optimizer = tf.train.AdamOptimizer(
```
[the remark this answers is not in the document]
Comment (seemuch) [reply official/recommendation/ncf_common.py]: Done.

File: official/recommendation/ncf_keras_main.py [hunk 27]
```diff
@@ -0,0 +1,218 @@
...
+
+def _keras_loss(y_true, y_pred):
+  loss = tf.losses.sparse_softmax_cross_entropy(
+      labels=tf.cast(y_true, tf.int32),
+      logits=y_pred)
+  return loss
+
+
+def _get_metric_fn(params):
+  """Get the metrix fn used by model compile."""
```
[the remark this answers is not in the document]
Comment (seemuch) [reply official/recommendation/ncf_keras_main.py]: Done.

File: official/recommendation/ncf_common.py (hunk 26 above)
[the remark this answers is not in the document]
Comment (robieta) [reply official/recommendation/ncf_common.py]: Yes, but given that we're pushing keras optimizers as the way of the future my question is can we use those in both paths instead?

[the remark this answers is not in the document]
Comment (seemuch) [reply official/recommendation/ncf_common.py]: I tried, and it failed for estimator.

File: official/recommendation/ncf_keras_main.py [hunk 28]
```diff
@@ -0,0 +1,218 @@
...
+
+  keras_model.compile(
+      loss=_keras_loss,
+      metrics=[_get_metric_fn(params)],
+      optimizer=optimizer)
+
+  train_input_dataset, eval_input_dataset = _get_train_and_eval_data(
+      producer, params)
+
+  keras_model.fit(
```
[the remark this answers is not in the document]
Comment (seemuch) [reply official/recommendation/ncf_keras_main.py]: There is a bug for passing validation_data to fit(). 
b/126902919

File: official/recommendation/run.sh (hunk 21 above)
Comment (seemuch) [reply official/recommendation/run.sh]: Done.

File: official/recommendation/ncf_common.py (hunk 26 above)
[the remark this answers is not in the document]
Comment (robieta) [reply official/recommendation/ncf_common.py]: Is there a bug filed? In any case, we don't need to block on it.

[the remark this answers is not in the document]
Comment (seemuch) [reply official/recommendation/ncf_common.py]: I am not sure if this is a bug. It looks like that it is not something wrong with `tf.keras.optimizers.Adam`, it is just API incompatibility.

**Comment by littlehome-eugene** [comment]
which version of tensorflow is required for working with this? I've tried 2.0.alpha and 1.13, but doesn't seem to work.

**Comment by seemuch** [comment]
@littlehome-eugene what is the error you were seeing, please?

**Comment by littlehome-eugene** [comment]
oh, 
```

File "/home/eugenekim/study-no/recommender/v2/models/official/utils/misc/distribution_utils.py", line 28, in <module>
    None: tf.distribute.experimental.CollectiveCommunication.AUTO,
AttributeError: 'module' object has no attribute 'experimental'
```

I am running it by commenting out the import for now.. (ncf_common.py  from official.utils.misc import distribution_utils)

**Comment by robieta** [comment]
Your version of tensorflow is out of date. Upgrade to the latest `tf-nightly` (or `tf-nightly-gpu`) and it should fix it.
