### ISSUE TITLE
TypeError: in method 'ReadFromStream', argument 2 of type 'size_t' in compression model

### ISSUE THREAD

**Issue by truboxl** [tensorflow/models#7862]
### System information
Google Colab

### Describe the problem
Tried to run [image_encoder compression model](https://github.com/tensorflow/models/tree/master/research/compression/image_encoder) in Colab, stuck at Comparing Similarity using msssim.py

Attached a written Colab file, just hit Run All:
https://colab.research.google.com/gist/truboxl/1c20fe7b6bc7ff52ceff9a39acdbd721/set-up-tf-models-compression-imageencoder.ipynb

### Source code / logs
Traceback (most recent call last):
  File "msssim.py", line 217, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "msssim.py", line 202, in main
    img1_str = image_file.read('rb')
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/lib/io/file_io.py", line 128, in read
    pywrap_tensorflow.ReadFromStream(self._read_buf, length))
TypeError: in method 'ReadFromStream', argument 2 of type 'size_t'

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by truboxl** [comment]
The Colab file also includes the commented line for outputting `cat tf_env.txt`... zzz

What is the top-level directory of the model you are using
models/research/compression/image_encoder

Have I written custom code
No, refer Colab file

OS Platform and Distribution
os: Linux
os kernel version: #1 SMP Thu Aug 8 02:47:02 PDT 2019
os release version: 4.14.137+
os platform: Linux-4.14.137+-x86_64-with-Ubuntu-18.04-bionic
linux distribution: ('Ubuntu', '18.04', 'bionic')
linux os distribution: ('Ubuntu', '18.04', 'bionic')
mac version: ('', ('', '', ''), '')
uname: uname_result(system='Linux', node='ec7cae62dad7', release='4.14.137+', version='#1 SMP Thu Aug 8 02:47:02 PDT 2019', machine='x86_64', processor='x86_64')
architecture: ('64bit', 'ELF')
machine: x86_64

TensorFlow installed from
Google Colab(?)

TensorFlow version
1.15.0
(2.0.0 straight up broke encoder.py decoder.py msssim.py with a different error)

Bazel version
bash: line 168: bazel: command not found

CUDA/cuDNN version
NVIDIA-SMI 440.33.01    Driver Version: 418.67       CUDA Version: 10.1

GPU model and memory
Tesla K80

Exact command to reproduce
python msssim.py --original_image=./example.png --compared_image=./output/image_15.png

**Comment by brkygokcen** [comment]
I edited the code in "msssim.py" file like below,

`201  with tf.gfile.FastGFile(FLAGS.original_image, 'rb') as image_file:`
`202    img1_str = image_file.read()`
`203  with tf.gfile.FastGFile(FLAGS.compared_image, 'rb') as image_file: `
`204    img2_str = image_file.read()`

Then it working now.

**Comment by ravikyram** [comment]
@truboxl 

Is this still an issue.Please, close this thread if your issue was resolved.Thanks!

**Comment by truboxl** [comment]
@ravikyram I think this can be closed once @brkygokcen changes are applied. I confirmed the changes are working with tf-gpu 1.15.

But then tf-gpu 2.x just broke again, probably a different issue...
```
Traceback (most recent call last):
  File "decoder.py", line 30, in <module>
    tf.flags.DEFINE_string('input_codes', None, 'Location of binary code file.')
AttributeError: module 'tensorflow' has no attribute 'flags'
```

**Comment by ravikyram** [comment]
@truboxl 

Can we close this issue and open new issue by filling issue template and by providing related code. Thanks!

**Comment by truboxl** [comment]
...this is still an issue, it is broken out of the box.

**Comment by truboxl** [comment]
https://github.com/tensorflow/models/tree/archive/research#warning-archived-models-and-implementations

Since the models are now archived, removed from master branch, no longer maintained and not updated for use with TF2,
I guess there's nothing I can do about anymore.

Closing issue...
