### ISSUE TITLE
ptb example not working

### ISSUE THREAD

**Issue by nebgru** [tensorflow/models#1039]
## models/tutorials/rnn/ptb/

When attempting to run the tut, there is the following error:

line 117, in ptb_producer
    [batch_size, (i + 1) * num_steps])
TypeError: strided_slice() missing 1 required positional argument: 'strides'

I'm running with python3, and adding strides=None does not help. Looks like this function cannot work without a stride specified.

**Comment by aselle** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

My guess is you are running a pre 1.0 tensorflow. Upgrading should fix that problem. You can also manually provide strides using a ones_like(x) where begin is the firsta argument to tf.strided_slice.

**Comment by nebgru** [comment]
Sorry for the missing info. The problem was with the Tensorflow version. It all works after the upgrade to 1.0. Did not realize it changed.
