### PR TITLE
add 'reuse' parameter to RNNCells to make code compatible with tensorflow master code

### PR DESCRIPTION
**Pull request by tongda**
To fix the issue mentioned in [#8191](https://github.com/tensorflow/tensorflow/issues/8191) caused by the [recent commit](https://github.com/tensorflow/tensorflow/commit/54d50ffec8df4f748694632dbe5ebde9971e2c9e) of TensorFlow master branch. As the commit message says:

> Make all RNNCells in tf.contrib.rnn act like tf.layers Layers, but with stricter semantics for no
w:
>
>    1. Upon first use of __call__, the used scope is stored in the cell. The RNNCell tries to create weights in that scope but if some are already set, an error is raised unless the RNNCell was constructed with argument reuse=True.
>
>    2. A subsequent use of __call__ of the same cell instance must be in the same scope.
>       If it is not, an error is raised.

### CODE REVIEW

**Comment by nealwu** [comment]
@ebrevdo does this change look correct to you?

**Comment by ebrevdo** [comment]
Yes, lgtm

**Comment by nealwu** [comment]
Super. Thanks!

**Comment by GBLin5566** [comment]
Yes, this commit will make error msg.

`__init__() got an unexpected keyword argument 'reuse'`

**Comment by ebrevdo** [comment]
What version of tensorflow are you using?

**Comment by GBLin5566** [comment]
@ebrevdo
My tf version is 1.0, and according to API r1.0 there is no argument 'reuse' in BasicLSTMCell.

**Comment by ebrevdo** [comment]
Ah, the model is based on tf nightlies.

**Comment by nealwu** [comment]
@ebrevdo is still there an issue? Given that this is a tutorial model, we want it to be compatible with TensorFlow 1.0, so if that's not the case with this we should revert.

**Comment by nealwu** [comment]
Going to revert this because we want the tutorial models to be compatible with TensorFlow 1.0, not just master. @tongda, does reverting this change cause serious issues for the model?

**Comment by ebrevdo** [comment]
The model won't work without this change in master.

**Comment by nealwu** [comment]
Do you know any good ways to make it worth for both versions? Given that this is a tutorial model and the vast majority of its users will be on 1.0, having it work on 1.0 is a must. If there's a way to fix it for both 1.0 and master at the same time, we can go for that.

**Comment by ebrevdo** [comment]
I'd prefer this tutorial check the tf version and fail if the wrong range
is installed.  This will be too hard to maintain for multiple versions of
contrib code.  Users of nightlies should have no expectation of
compatibility in contrib with any published code.

**Comment by nealwu** [comment]
Sure, what should that look like? `if not tf.__version__.startswith('1.0')` then raise an error?

**Comment by nealwu** [comment]
Looks like that won't work. Even if you install from source right now, your `tf.__version__` will be `1.0.1`.

**Comment by ebrevdo** [comment]
Yeah, there's a git version baked in somewhere but I'm not sure if we can
check it as an ordinal.  We should check with the release team to ensure
they increment the master version number after each release.

**Comment by tongda** [comment]
How about we add a `try... catch` of `KeyError` during the transitional period of new api?

**Comment by nealwu** [comment]
Not the most elegant option but it works. I'll add a new pull request.

**Comment by llealgt** [comment]
Hello, is any of this related to this error: Trying to share variable rnn/multi_rnn_cell/cell_0/basic_lstm_cell/weights, but specified shape (1024, 2048) and found shape (595, 2048).
Can you take a look, im running this code (from udacity course) : https://github.com/udacity/deep-learning/blob/master/intro-to-rnns/Anna_KaRNNa.ipynb

**Comment by ebrevdo** [comment]
What version of tf are you using?

**Comment by llealgt** [comment]
1.0 , I builded from code pulling from master branch like a week ago.
