### ISSUE TITLE
sequence to sequence model error

### ISSUE THREAD

**Issue by ymakkapa** [tensorflow/models#1050]
## Please let us know which model this issue is about (specify the top-level directory)
Hello everyone,
I am getting the following errors after executing translate.py

Can anyone please help me in resolving this error
Thanks in advance
![sotierror](https://cloud.githubusercontent.com/assets/20130992/23184238/0c38637a-f84d-11e6-8a4d-282607ec280c.png)

**Comment by tatatodd** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by ymakkapa** [comment]
Hello,
I am using ubuntu 16.04 LTS on vmware with RAM 2gb and disk space 100 GB. 
Tensorflow version is 1.0

**Comment by tatatodd** [comment]
@ymakkapa Can you also show the complete command-line you ran that caused the error?  Thanks!

**Comment by mhnatiuk** [comment]
you shouldn't use tf.contrib.seq2seq anymore. just do:
from tensorflow.python.ops import rnn_cell
and then: 
rnn_cell.GRUCell(size)

**Comment by ymakkapa** [comment]
Hi @tatatodd ,
This is the command line - python translate.py --data_dir [your_data_directory]

**Comment by ymakkapa** [comment]
@mhnatiuk , Should I make these changes in translate.py file

**Comment by ymakkapa** [comment]
Hi @mhnatiuk ,
I checked all my files but could not find the line gave by you in any of my files

**Comment by prb12** [comment]
@ymakkapa  I guess you're following https://www.tensorflow.org/tutorials/seq2seq?

The tutorial does not seem to have been update for TF1.0 yet.  @ebrevdo, @xmbrst Is this the case?  Who is responsible for ensuring all our tutorials work with the current release version?

As mentioned above, the GRUCell class appears to have moved.  It is being instantiated in the file seq2seq_model.py

Hopefully this will help you work around the problem for now.

**Comment by ymakkapa** [comment]
Yes @prb12 . But I am getting the above error. Regarding TF version, i did not upgrade it to 1.0

**Comment by ebrevdo** [comment]
Lukasz, can you update the tutorial?

**Comment by lukaszkaiser** [comment]
I think we decided to wait for the new tutorial, there are many problems with the old one and it's going away very soon (I hope).

**Comment by ebrevdo** [comment]
We should Mark it as deprecated and fix any small bugs until the new one is
ready.

**Comment by prb12** [comment]
+1 to @ebrevdo 's suggestion!

**Comment by ymakkapa** [comment]
Hello everyone,
Can I get the link of the updated code for sequence to sequence models tutorial?

**Comment by mhnatiuk** [comment]
following @ebrevdo talk on sequence to sequence models @ tfsummit I decided to try dynamic decoding. Unfortunately, with so many options it's difficult to wire things up fast. When are you planning to release some code showing new features?

**Comment by ebrevdo** [comment]
Within the next month, hopefully.

**Comment by ymakkapa** [comment]
Hello everyone,
Thanks a lot for your time and information. I deleted everything, re-installed tensorflow and getting the following errors. I am a beginner to tensorflow and need your help. 
![mostrecentseqerror](https://cloud.githubusercontent.com/assets/20130992/24421329/db269f30-13c3-11e7-896c-df3c9919dfdb.PNG)

**Comment by mhnatiuk** [comment]
Looks like you have a problem with permissions to write to tmp folder, the issue has nothing to do with tensorflow itself as far as I see. This question is better suited for stackoverflow though

**Comment by ymakkapa** [comment]
HI, I deleted everything and installed Ubuntu 16.04.2 LTS and the output processed for a long time and got errors again. I got the code from "https://github.com/tensorflow/models/tree/master/tutorials/rnn/translate" and got the following errors. Can anyone please help me with this. I did not upgrade to tensorflow 1.0
![fresh error seq](https://cloud.githubusercontent.com/assets/20130992/24465395/dbb98afe-147a-11e7-86cb-66a7fa234263.PNG)

**Comment by smolendawid** [comment]
@ebrevdo Is there any chance for the tutorial/code to be updated? (as you mentioned few posts earlier?)

**Comment by Vimos** [comment]
Using tensorflow r1.2, I got the error below:
```
➜  translate git:(master) ✗ python translate.py --data_dir ~/Public/data/nmt/nmt --train_dir train_dir  --en_vocab_size=40000 --fr_vocab_size=40000 --steps_per_checkpoint=50 --size=256 --num_layers=2
Preparing WMT data in /home/vimos/Public/data/nmt/nmt
2017-05-25 17:41:48.950970: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:893] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-05-25 17:41:48.951456: I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] Found device 0 with properties: 
name: GeForce GTX 970M
major: 5 minor: 2 memoryClockRate (GHz) 1.038
pciBusID 0000:01:00.0
Total memory: 2.95GiB
Free memory: 2.28GiB
2017-05-25 17:41:48.951479: I tensorflow/core/common_runtime/gpu/gpu_device.cc:927] DMA: 0 
2017-05-25 17:41:48.951485: I tensorflow/core/common_runtime/gpu/gpu_device.cc:937] 0:   Y 
2017-05-25 17:41:48.951499: I tensorflow/core/common_runtime/gpu/gpu_device.cc:996] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 970M, pci bus id: 0000:01:00.0)
Creating 2 layers of 256 units.
Traceback (most recent call last):
  File "translate.py", line 322, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "translate.py", line 319, in main
    train()
  File "translate.py", line 178, in train
    model = create_model(sess, False)
  File "translate.py", line 136, in create_model
    dtype=dtype)
  File "/data/home/vimos/Public/git/github/ml/tensorflow/models/tutorials/rnn/translate/seq2seq_model.py", line 179, in __init__
    softmax_loss_function=softmax_loss_function)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/legacy_seq2seq/python/ops/seq2seq.py", line 1207, in model_with_buckets
    decoder_inputs[:bucket[1]])
  File "/data/home/vimos/Public/git/github/ml/tensorflow/models/tutorials/rnn/translate/seq2seq_model.py", line 178, in <lambda>
    lambda x, y: seq2seq_f(x, y, False),
  File "/data/home/vimos/Public/git/github/ml/tensorflow/models/tutorials/rnn/translate/seq2seq_model.py", line 142, in seq2seq_f
    dtype=dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/legacy_seq2seq/python/ops/seq2seq.py", line 849, in embedding_attention_seq2seq
    encoder_cell = copy.deepcopy(cell)
  File "/usr/lib/python2.7/copy.py", line 174, in deepcopy
    y = copier(memo)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/layers/base.py", line 474, in __deepcopy__
    setattr(result, k, copy.deepcopy(v, memo))
  File "/usr/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.7/copy.py", line 230, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/usr/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.7/copy.py", line 230, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/usr/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.7/copy.py", line 230, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/usr/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.7/copy.py", line 237, in _deepcopy_tuple
    y.append(deepcopy(a, memo))
  File "/usr/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python2.7/copy.py", line 343, in _reconstruct
    y.__dict__.update(state)
AttributeError: 'NoneType' object has no attribute 'update'
```

**Comment by syw2014** [comment]
@Vimos have you solved the issue? I had the same issue too, any suggestions, thx?

**Comment by OliveirShi** [comment]
same error and same problem! @syw2014

**Comment by Sanghoon94** [comment]
Which version of tensorflow can I use to evade the errors?

**Comment by ebrevdo** [comment]
I've found the bug in TF 1.2.  I will submit a fix, and it will appear in
the nightlies (not in TF 1.2).  The will then be fixed in TF 1.3 when that
is released.

**Comment by Sanghoon94** [comment]
For the time being, I've checked that the seq2seq translation works fine in TF 1.0

**Comment by ucaslyc** [comment]
@ebrevdo Using tensorflow 1.3, I still got the error like Vimos described above. It seems that it hasn't been fixed in TF 1.3. Or could you please tell me where the bug is?

**Comment by mikeal** [comment]
Same issue on 1.3.

**Comment by ebrevdo** [comment]
I'll take a look. Unfortunately this tutorial is deprecated in favor of

https://github.com/tensorflow/nmt

So it's getting less attention.  We need to update the tf.org tutorial link to point to the nmt codebase.

**Comment by Schweboo** [comment]
Given the number of people who have used the original tutorial to develop other projects (e.g. chatbots), this is disappointing. Will the bugs found in the initial tutorial be fixed?

**Comment by jkneng** [comment]
same error with @Vimos using 1.2.1 . Any update?

**Comment by jkneng** [comment]
I found https://github.com/tensorflow/nmt. It is a new seq2seq tutorial for this isssue?

**Comment by Schweboo** [comment]
Uses the nightly TF version:
"This version of the tutorial requires TensorFlow Nightly. For using the stable TensorFlow versions, please consider other branches such as tf-1.2."

"Nightly pip packages

We are pleased to announce that TensorFlow now offers nightly pip packages under the tf-nightly and tf-nightly-gpu project on pypi. Simply run pip install tf-nightly or pip install tf-nightly-gpu in a clean environment to install the nightly TensorFlow build. We support CPU and GPU packages on Linux, Mac, and Windows.
Individual whl files

Linux CPU-only: Python 2 (build history) / Python 3.4 (build history) / Python 3.5 (build history)
Linux GPU: Python 2 (build history) / Python 3.4 (build history) / Python 3.5 (build history)
Mac CPU-only: Python 2 (build history) / Python 3 (build history)
Windows CPU-only: Python 3.5 64-bit (build history) / Python 3.6 64-bit (build history)
Windows GPU: Python 3.5 64-bit (build history) / Python 3.6 64-bit (build history)
Android: demo APK, native libs (build history)"

**Comment by karmel** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow, and using the preferred version of the tutorial linked above. Thank you.

**Comment by vltabacaru** [comment]
Any fix on this?
Using tensorflow 1.10.0.
```
$ python2 execute.py

>> Mode : train

Preparing data in working_dir/
2018-08-14 12:07:03.775578: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Creating 3 layers of 256 units.
2018-08-14 12:07:04.514468: W tensorflow/python/util/util.cc:159] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
Traceback (most recent call last):
  File "execute.py", line 319, in <module>
    train()
  File "execute.py", line 137, in train
    model = create_model(sess, False)
  File "execute.py", line 104, in create_model
    model = seq2seq_model.Seq2SeqModel( gConfig['enc_vocab_size'], gConfig['dec_vocab_size'], _buckets, gConfig['layer_size'], gConfig['num_layers'], gConfig['max_gradient_norm'], gConfig['batch_size'], gConfig['learning_rate'], gConfig['learning_rate_decay_factor'], forward_only=forward_only)
  File "/home/oracle/Git/tensorflow_chatbot/seq2seq_model.py", line 162, in __init__
    softmax_loss_function=softmax_loss_function)
  File "/usr/lib/python2.7/site-packages/tensorflow/contrib/legacy_seq2seq/python/ops/seq2seq.py", line 1215, in model_with_buckets
    decoder_inputs[:bucket[1]])
  File "/home/oracle/Git/tensorflow_chatbot/seq2seq_model.py", line 161, in <lambda>
    lambda x, y: seq2seq_f(x, y, False),
  File "/home/oracle/Git/tensorflow_chatbot/seq2seq_model.py", line 125, in seq2seq_f
    feed_previous=do_decode)
  File "/usr/lib/python2.7/site-packages/tensorflow/contrib/legacy_seq2seq/python/ops/seq2seq.py", line 857, in embedding_attention_seq2seq
    encoder_cell = copy.deepcopy(cell)
  File "/usr/lib64/python2.7/copy.py", line 174, in deepcopy
    y = copier(memo)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 383, in __deepcopy__
    setattr(result, k, copy.deepcopy(v, memo))
  File "/usr/lib64/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.7/copy.py", line 230, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/usr/lib64/python2.7/copy.py", line 174, in deepcopy
    y = copier(memo)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 383, in __deepcopy__
    setattr(result, k, copy.deepcopy(v, memo))
  File "/usr/lib64/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.7/copy.py", line 230, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/usr/lib64/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib64/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib64/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib64/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib64/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib64/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib64/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib64/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib64/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.7/copy.py", line 230, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/usr/lib64/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib64/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib64/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib64/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib64/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib64/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib64/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.7/copy.py", line 230, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/usr/lib64/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.7/copy.py", line 237, in _deepcopy_tuple
    y.append(deepcopy(a, memo))
  File "/usr/lib64/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib64/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib64/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib64/python2.7/copy.py", line 343, in _reconstruct
    y.__dict__.update(state)
AttributeError: 'NoneType' object has no attribute 'update'
```
