### ISSUE TITLE
model_main.py tries to import unavailable libraries in tensorflow v2

### ISSUE THREAD

**Issue by john-khgoh** [tensorflow/models#8332]
I'm trying to run models/research/objection_detection/model_main.py. It calls eval_utils.py which contains this line:

slim = tf.contrib.slim

Currently **tensorflow v2 does not have the tf.contrib library** anymore. This is the error I get:

`Traceback (most recent call last):
  File "model_main.py", line 26, in <module>
    from object_detection import model_lib
  File "C:\Users\Me\Documents\Project 2018\07_imagerec\Tensorflow\models\research\object_detection\model_lib.py", line 27, in <module>
    from object_detection import eval_util
  File "C:\Users\Me\Documents\Project 2018\07_imagerec\Tensorflow\models\research\object_detection\eval_util.py", line 35, in <module>
    slim = tf.contrib.slim
AttributeError: module 'tensorflow' has no attribute `'contrib'`

I did however find someone with a similar issue and the solution proposed is to use "tf_slim" package. This solve the particular error above but further in hits another error which is also due to calling from tensorflow.contrib

`2020-03-26 22:47:22.437429: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
Traceback (most recent call last):
  File "model_main.py", line 26, in <module>
    from object_detection import model_lib
  File "C:\Users\Me\Documents\Project 2018\07_imagerec\Tensorflow\models\research\object_detection\model_lib.py", line 27, in <module>
    from object_detection import eval_util
  File "C:\Users\Me\Documents\Project 2018\07_imagerec\Tensorflow\models\research\object_detection\eval_util.py", line 34, in <module>
    import tf_slim as slim
  File "C:\Users\Me\AppData\Local\Programs\Python\Python36\lib\site-packages\tf_slim\__init__.py", line 23, in <module>
    from tf_slim import evaluation
  File "C:\Users\Me\AppData\Local\Programs\Python\Python36\lib\site-packages\tf_slim\evaluation.py", line 131, in <module>
    from tensorflow.contrib.training.python.training import evaluation
  File "C:\Users\Me\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\contrib\training\__init__.py", line 58, in <module>
    from tensorflow.contrib.training.python.training.hparam import *
  File "C:\Users\Me\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\contrib\training\python\training\hparam.py", line 26, in <module>
    from tensorflow.contrib.training.python.training import hparam_pb2
ImportError: cannot import name 'hparam_pb2'`

Is there a workaround or does the model_main.py need to be updated?

**Comment by saberkun** [comment]
Please use TF 1.15 for objection_detection.

**Comment by elvinest** [comment]
When will it be update to support tf2.x？

**Comment by john-khgoh** [comment]
I hope there will be an updated version that supports tf2.x because of dependency issues. TF 1.15 works with the older version of Nvidia CUDA toolkit and CuDNN but those are not compatible with another program I need to use. I'm sure there are others who face the same issue.

**Comment by PhilipMay** [comment]
I am also interested in an TF 2.0 migration.

**Comment by joshd-7** [comment]
I'm also interested. Is this being worked on yet or is there a rough timeline?

**Comment by tombstone** [comment]
@john-khgoh  Slim imports are fixed now, but model_main.py only works with TF 1.15 at the moment as others pointed out.

**Comment by tombstone** [comment]
We are targeting TF2 support by end of June approximately.
