### PR TITLE
Fixed dataset_utils.py for tensorflow 1.1 by removing decode() after file reading.

### PR DESCRIPTION
**Pull request by andreas-eberle**
With tensorflow 1.1 I experienced the following exception with code that was working fine with tensorflow 1.0.

```
Traceback (most recent call last):
  File "eval_for_features.py", line 266, in <module>
    tf.app.run()
  File "/home/aeberle/.local/lib/python3.4/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "eval_for_features.py", line 118, in main
    evaluate_split('query')
  File "eval_for_features.py", line 142, in evaluate_split
    FLAGS.dataset_name, split_name, FLAGS.dataset_dir)
  File "/home/aeberle/development/masters/tensorflow-models/slim/datasets/dataset_factory.py", line 59, in get_dataset
    reader)
  File "/home/aeberle/development/masters/tensorflow-models/slim/datasets/market1501.py", line 86, in get_split
    labels_to_names = dataset_utils.read_label_file(dataset_dir)
  File "/home/aeberle/development/masters/tensorflow-models/slim/datasets/dataset_utils.py", line 129, in read_label_file
    lines = f.read().decode()
AttributeError: 'str' object has no attribute 'decode'
```

With this PR, I remove the decode() operation which no longer seems to be needed.

### CODE REVIEW

**Comment by nealwu** [comment]
Hi @andreas-eberle, is there a way to fix this that works for both TF 1.1 and 1.0? We don't want to break backwards compatibility.

**Comment by andreas-eberle** [comment]
Actually, I don't know. I just experienced this and trial-and-errored myself to the fix...

**Comment by sguada** [comment]
I signed

**Comment by nealwu** [comment]
@sguada the "CLA:no" label can just be ignored in this case. However it looks like there are no files changed?
