### ISSUE TITLE
line 195 in build_image_embeddings    tf.GraphKeys.GLOBAL_VARIABLES, scope="InceptionV3") AttributeError: type object 'GraphKeys' has no attribute 'GLOBAL_VARIABLES'

### ISSUE THREAD

**Issue by prokopevaleksey** [tensorflow/models#742]
I encounter

> line 195 in build_image_embeddings tf.GraphKeys.GLOBAL_VARIABLES, scope="InceptionV3")
> AttributeError: type object 'GraphKeys' has no attribute 'GLOBAL_VARIABLES'

when I try to run readme example using pretrained model executing

> bazel-bin/im2txt/run_inference   --checkpoint_path=${CHECKPOINT_DIR}   --vocab_file=${VOCAB_FILE}   --input_files=${IMAGE_FILE}

Please, let me know about additional information you may need. Thank you in advance.

**Comment by nishkaks** [comment]
I got the same error with the older version of tensorflow - '0.11.0rc0'. Try upgrading it to 12.

**Comment by albertbuchard** [comment]
What does this error mean, I get the same error ...

**Comment by mehdimo** [comment]
got a same error.

**Comment by yselivonchyk** [comment]
Got the same error after upgrading TF to 0.12 and downgrading it back to 0.10

**Comment by karmel** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.
