### ISSUE TITLE
AttributeError: module 'tensorflow.python.training.tracking.tracking' has no attribute 'cached_per_instance'

### ISSUE THREAD

**Issue by milos-cuculovic** [tensorflow/models#9376]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://www.tensorflow.org/official_models/fine_tuning_bert

## 2. Describe the bug

While trying to execute the 
bert_classifier, bert_encoder = bert.bert_models.classifier_model(bert_config, num_labels=2), the following message appears:

```
AttributeError: module 'tensorflow.python.training.tracking.tracking' has no attribute 'cached_per_instance'
  In call to configurable 'get_transformer_encoder' (<function get_transformer_encoder at 0x7fa62ead65e0>)

```

## 3. Steps to reproduce

Steps to reproduce the behavior: run until the line 
bert_classifier, bert_encoder = bert.bert_models.classifier_model(bert_config, num_labels=2)

## 4. Expected behavior

Run this without errors.

## 5. Additional context

```
AttributeError                            Traceback (most recent call last)
<ipython-input-58-70c6d92a29c6> in <module>
----> 1 bert_classifier, bert_encoder = bert.bert_models.classifier_model(
      2     bert_config, num_labels=2)

~/opt/anaconda3/lib/python3.8/site-packages/official/nlp/bert/bert_models.py in classifier_model(bert_config, num_labels, max_seq_length, final_layer_initializer, hub_module_url, hub_module_trainable)
    341 
    342   if not hub_module_url:
--> 343     bert_encoder = get_transformer_encoder(
    344         bert_config, max_seq_length, output_range=1)
    345     return models.BertClassifier(

~/opt/anaconda3/lib/python3.8/site-packages/gin/config.py in gin_wrapper(*args, **kwargs)
   1076       scope_info = " in scope '{}'".format(scope_str) if scope_str else ''
   1077       err_str = err_str.format(name, fn_or_cls, scope_info)
-> 1078       utils.augment_exception_message_and_reraise(e, err_str)
   1079 
   1080   return gin_wrapper

~/opt/anaconda3/lib/python3.8/site-packages/gin/utils.py in augment_exception_message_and_reraise(exception, message)
     47   if six.PY3:
     48     ExceptionProxy.__qualname__ = type(exception).__qualname__
---> 49     six.raise_from(proxy.with_traceback(exception.__traceback__), None)
     50   else:
     51     six.reraise(proxy, None, sys.exc_info()[2])

~/opt/anaconda3/lib/python3.8/site-packages/six.py in raise_from(value, from_value)

~/opt/anaconda3/lib/python3.8/site-packages/gin/config.py in gin_wrapper(*args, **kwargs)
   1053 
   1054     try:
-> 1055       return fn(*new_args, **new_kwargs)
   1056     except Exception as e:  # pylint: disable=broad-except
   1057       err_str = ''

~/opt/anaconda3/lib/python3.8/site-packages/official/nlp/bert/bert_models.py in get_transformer_encoder(bert_config, sequence_length, transformer_encoder_cls, output_range)
    173     assert isinstance(bert_config, configs.BertConfig)
    174     kwargs['output_range'] = output_range
--> 175     return networks.TransformerEncoder(**kwargs)
    176 
    177 

~/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py in __new__(cls, *args, **kwargs)
    219     def call(self, inputs, training=False):
    220       x = self.dense1(inputs)
--> 221       if training:
    222         x = self.dropout(x, training=training)
    223       return self.dense2(x)

~/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/utils/version_utils.py in __new__(cls, *args, **kwargs)
     63   def __new__(cls, *args, **kwargs):  # pylint: disable=unused-argument
     64     use_v2 = should_use_v2()
---> 65     cls = swap_class(cls, base_layer.Layer, base_layer_v1.Layer, use_v2)  # pylint: disable=self-cls-assignment
     66     return super(LayerVersionSelector, cls).__new__(cls)
     67 

~/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/utils/generic_utils.py in __getattr__(self, item)

~/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/utils/generic_utils.py in _load(self)

~/opt/anaconda3/lib/python3.8/importlib/__init__.py in import_module(name, package)
    125                 break
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128 
    129 

~/opt/anaconda3/lib/python3.8/importlib/_bootstrap.py in _gcd_import(name, package, level)

~/opt/anaconda3/lib/python3.8/importlib/_bootstrap.py in _find_and_load(name, import_)

~/opt/anaconda3/lib/python3.8/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

~/opt/anaconda3/lib/python3.8/importlib/_bootstrap.py in _load_unlocked(spec)

~/opt/anaconda3/lib/python3.8/importlib/_bootstrap_external.py in exec_module(self, module)

~/opt/anaconda3/lib/python3.8/importlib/_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

~/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer_v1.py in <module>
     75 
     76 # pylint: disable=g-classes-have-attributes
---> 77 class Layer(base_layer.Layer):
     78   """Base layer class.
     79 

~/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer_v1.py in Layer()
   2315 
   2316   @property
-> 2317   @tracking.cached_per_instance
   2318   def _call_full_argspec(self):
   2319     # Argspec inspection is expensive and the call spec is used often, so it

AttributeError: module 'tensorflow.python.training.tracking.tracking' has no attribute 'cached_per_instance'
  In call to configurable 'get_transformer_encoder' (<function get_transformer_encoder at 0x7fa62ead65e0>)
```

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): OSx Catalina
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.3.1 - python3 -c 'import tensorflow as tf; print(tf.__version__)'
- Python version: Python 3.8.5

**Comment by saberkun** [comment]
Hi @milos-cuculovic, this is the first time we see this error. 
Do you disable the v2 eager behavior? Why base_layer_v1.py is used... 
@chenGitHuber Does this colab still work?

**Comment by chenGitHuber** [comment]
Hi @milos-cuculovic 

I just verified that the following colab still works:

https://colab.sandbox.google.com/github/tensorflow/models/blob/master/official/colab/fine_tuning_bert.ipynb

Which tf-models pip package did you use? Sorry that the page in https://www.tensorflow.org/official_models/fine_tuning_bert suggests to use "tf-models-nightly", but actually this colab should work with tf-models-official==2.3.0.

**Comment by saberkun** [comment]
@chenGitHuber Should we reach out the doc team to update?
https://www.tensorflow.org/official_models/fine_tuning_bert

**Comment by scotthoule** [comment]
Friendly ping.

**Comment by chenGitHuber** [comment]
Hi @scotthoule, I just verified that the colab works and also the link https://www.tensorflow.org/official_models/fine_tuning_bert has been updated. Did you still see this issue?
