### ISSUE TITLE
AttributeError: module tensorflow has no attribute contrib

### ISSUE THREAD

**Issue by Girish1127** [tensorflow/models#7767]
version: python 3.6.9
OS: windows10
IDE: anaconda, spyder (executing locally)
also installed tensorflow by creating new environment in anaconda (without using pip)
tensorflow version 2.0.0

code shown below:
import tensorflow as tf
''''
'''''
init_kernel = tf.contrib.layers.xavier_initializer()
getting error for the above line.
AttributeError: module 'tensorflow' has no attribute 'contrib'

**Comment by gaseosaluz** [comment]
Since you say that you used TF 2.0, from the TF docs:

https://www.tensorflow.org/guide/upgrade#compatibility_modules

I gather (but I could be wrong) that `tf.contrib` is not available on TF 2.0 (At least not all of the functionality). 

These discussion maybe helpful? 
https://github.com/tensorflow/tensorflow/issues/26854
https://github.com/tensorflow/community/pull/18

**Comment by sinakhani** [comment]
Hello there,
When I use 
initializer = tf.contrib.layers.xavier_initializer(seed = 0)) 
to initialize my ML layer I get the following error
AttributeError: module 'tensorflow' has no attribute 'contrib'
Any suggestion to remove this error is really appreciated.

**Comment by EduardoABarrera** [comment]
tensorflow.contrib was removed in TF2. Tensorflow Core released a utility to convert your TF 1.x scripts to TF2.0 which can be found here: https://www.tensorflow.org/guide/upgrade

**Comment by mrhanti** [comment]
@EduardoABarrera parts of [tensorflow/models](https://github.com/tensorflow/models/blob/master/research/object_detection/predictors/convolutional_box_predictor.py) latest code base are still using the TF 1.x API. 

For instance: 

```
...
from object_detection.utils import static_shape

// Throws: AttributeError: module 'tensorflow' has no attribute 'contrib'
slim = tf.contrib.slim

BOX_ENCODINGS = box_predictor.BOX_ENCODINGS
...
```
Find the complete file [here](https://github.com/tensorflow/models/blob/master/research/object_detection/predictors/convolutional_box_predictor.py)

This is causing problems when doing transfer learning on object detection models. Do you have any idea or workaround for this one?

**Comment by EduardoABarrera** [comment]
> @EduardoABarrera parts of [tensorflow/models](https://github.com/tensorflow/models/blob/master/research/object_detection/predictors/convolutional_box_predictor.py) latest code base are still using the TF 1.x API.
> 
> For instance:
> 
> ```
> ...
> from object_detection.utils import static_shape
> 
> // Throws: AttributeError: module 'tensorflow' has no attribute 'contrib'
> slim = tf.contrib.slim
> 
> BOX_ENCODINGS = box_predictor.BOX_ENCODINGS
> ...
> ```
> 
> Find the complete file [here](https://github.com/tensorflow/models/blob/master/research/object_detection/predictors/convolutional_box_predictor.py)
> 
> This is causing problems when doing transfer learning on object detection models. Do you have any idea or workaround for this one?

@mrhanti I also bumped into this problem, and it turns out that the library `tf.contrib` is the only library that isn't converted via the utility mentioned above. If you're trying to convert a model like AlexNet that was written in TF1.X to a version of AlexNet written in TF2.0, I don't think there is a simple solution for that. I detailed this same problem (almost?) in [`this Stack overflow post`](https://stackoverflow.com/questions/59863288/converting-alexnet-from-tensorflow-1-x-to-tensorflow-2-0).

The third point in my Stack overflow post is what I had to end up doing (writing out the model architecture by hand after converting it a few times), and it involved a lot of work. Sorry to bear bad news. :(

**Comment by IsaacPatole** [comment]
So there is no easy way out for this? @EduardoABarrera

**Comment by pbanikk** [comment]
[https://www.tensorflow.org/api_docs/python/tf/compat/v1/nn/rnn_cell/BasicLSTMCell](url)
The only workaround if you want to use Basic LSTM Cell.

**Comment by pourya-farzi** [comment]
The unwinding path is just this line :
!pip install tensorflow==1.14 
better than getting involved in convoluted procedure

**Comment by mikechen66** [comment]
For the usage in LSTM, it have changed to the following. 

```
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior() 
# -outputs, states = tf.contrib.rnn.static_rnn(lstm_cells, _X, dtype=tf.float32)
outputs, states = tf.compat.v1.nn.static_rnn(lstm_cells, _X, dtype=tf.float32)
```

And then it works. However, contrib is used widely in TensorFlow 1.x,  it is no integrated solution to the contrib problem. For instance, it is another solution to the contrib case. 

```
# -initializer = tf.contrib.layers.xavier_initializer(seed = 1)
initializer = tf.truncated_normal_initializer(stddev=0.1)
```

It is the pain of TensorFlow 2.x by the Google Team, So we need to solve it case by case.

**Comment by saookami** [comment]
My Tensorflow version is 2.1.0，I checked file where in tensorflow\contrib.
There's just a little bit of code here.
Like i found slim film but there's have nothion in it,

**Comment by pnmartinez** [comment]
> The unwinding path is just this line :
> !pip install tensorflow==1.14
> better than getting involved in convoluted procedure

I would add: create a specific environment for this and use it for TF1 stuff. You can do that in conda like:

```
conda create --name tf1 python=3.7  # python 3.8 won't work!
```

Then you can happily:

``` 
conda install tensorflow==1.14
```

**Comment by engsbk** [comment]
I have a similar problem with this line:
```python
        self.optimizer = tf.compat.v1.contrib.opt.ScipyOptimizerInterface(self.loss, 
                                                                method = 'L-BFGS-B', 
                                                                options = {'maxiter': 50000,
                                                                           'maxfun': 50000,
                                                                           'maxcor': 50,
                                                                           'maxls': 50,
                                                                           'ftol' : 1.0 * np.finfo(float).eps})
        
        init = tf.global_variables_initializer()
        self.sess.run(init)
```

It throws:
`AttributeError: module 'tensorflow._api.v2.compat.v1' has no attribute 'contrib'`

Any suggestion is appreciated. Thanks!

**Comment by gholn** [comment]
Please check if your PYTHONPATH is set. If it is not set, you can get this error of 'has no attribute 'contrib''.
In Windows, set PYTHONPATH in System Environment variables.
In Linus, set it by $export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim
Or you can add it to '.bashrc' file

**Comment by sandeep22-v** [comment]
export PYTHONPATH=$PYTHONPATH:pwd:pwd/slim
This will help surely..thank me later

**Comment by Fado2021** [comment]
@engsbk Hello,
Please how do you solved your issue??
 
AttributeError: module 'tensorflow._api.v2.compat.v1' has no attribute 'contrib'

**Comment by engsbk** [comment]
> @engsbk Hello,
> Please how do you solved your issue??
> 
> AttributeError: module 'tensorflow._api.v2.compat.v1' has no attribute 'contrib'


You can solve this in one of two ways:
- you can entirely remove Tensorflow v1.x and install Tensorflow v2.x
- Or Install Tensorflow v2.x and make sure it in the PATH directory.

**Comment by Fado2021** [comment]
Thanks you.

Le mar. 16 mars 2021 à 20:01, Shaikha Alkhuder ***@***.***> a
écrit :

**Comment by Fado2021** [comment]
@engsbk I tried your suggestion, but still have problems. Any help??

TensorFlow 2.0.0 + Keras 2.3.1 on Python 3.6.

Problem1: config = tf.ConfigProto()
AttributeError: module 'tensorflow' has no attribute 'ConfigProto'

Problem2: self.optimizer = tf.contrib.opt.ScipyOptimizerInterface(self.loss,
                                                                method='L-BFGS-B',
                                                                options={'maxiter': 20000,
                                                                         'maxfun': 50000,
                                                                         'maxcor': 50,
                                                                         'maxls': 50,
                                                                         'ftol': 1 * np.finfo(float).eps})
AttributeError: module 'tensorflow_core.compat.v1' has no attribute 'contrib'

![p1](https://user-images.githubusercontent.com/80686822/111416875-b710ce80-871f-11eb-92fd-4ba4775c2104.PNG)

**Comment by fdsig** [comment]
On Linux only:

`sudo apt updat 

update-alternatives --install /usr/bin/python python /usr/opt/python3.7  

virtualenv -p python3.7 contrib/**insert your path/and name for virtual environment)

source **insert/path/to/environment**/bin/activate 

pip install tensorflow==1.** `

As mentioned above this wont work on python 3.7 or later. 

useful links are:

[https://www.tensorflow.org/guide/migrate](https://www.tensorflow.org/guide/migrate)

Python alternative install on Linux:

[
https://medium.com/analytics-vidhya/how-to-install-and-switch-between-different-python-versions-in-ubuntu-16-04-dc1726796b9b](
https://medium.com/analytics-vidhya/how-to-install-and-switch-between-different-python-versions-in-ubuntu-16-04-dc1726796b9b)

[https://hackersandslackers.com/multiple-versions-python-ubuntu/](https://hackersandslackers.com/multiple-versions-python-ubuntu/)

python source download urls:

[https://www.python.org/ftp/python/3.7.0/](https://www.python.org/ftp/python/3.7.0/)

managing virtual environments Linux:

[https://www.liquidweb.com/kb/creating-virtual-environment-ubuntu-16-04/](https://www.liquidweb.com/kb/creating-virtual-environment-ubuntu-16-04/)

[https://docs.python.org/3/library/venv.html](https://docs.python.org/3/library/venv.html)

haveing tried most of the above- including migrating code and `import tensorflow.compat.v1 as tf
tf.disable_v2_behavior() ` which both are not viable workaround for code that uses the config module.

I was sucesfull able to run code with the above method without issue. 

Hope this help :-)

**Comment by Leci37** [comment]
Replace TF V1 line
`slim = tf.contrib.slim`
for  TF V2 
`import tf_slim as slim`

**Comment by Rooney445** [comment]
> version: python 3.6.9 OS: windows10 IDE: anaconda, spyder (executing locally) also installed tensorflow by creating new environment in anaconda (without using pip) tensorflow version 2.0.0
> 
> code shown below: import tensorflow as tf '''' ''''' init_kernel = tf.contrib.layers.xavier_initializer() getting error for the above line. AttributeError: module 'tensorflow' has no attribute 'contrib'

The "attributeerror: module tensorflow has no attribute contrib" error occurs in Python when we try to import or use tf.contrib in TensorFlow 2.0 or later versions. This is because tf.contrib has been removed from TensorFlow 2.0.

To fix this error we need to downgrade the tensorflow to the version that supports the tf.contrib or upgrade the code from 1.x version to 2.x version. You can check this [guide ](https://pythonial.com/attributeerror-module-tensorflow-has-no-attribute-contrib/) to resolve this error, I have found it very helpful.

**Comment by Rooney445** [comment]
check this tutorial to resolve this error: https://pythonial.com/attributeerror-module-tensorflow-has-no-attribute-contrib/

**Comment by Ayad-Mihidabi-Khan-Jitu** [comment]
> Replace TF V1 line `slim = tf.contrib.slim` for TF V2 `import tf_slim as slim`

**THANKSSSSS IT WORKSSSS**

**Comment by shravani1115** [comment]
AttributeError: module 'tensorflow' has no attribute 'contrib' facing this error please help

**Comment by shravani1115** [comment]
> Replace TF V1 line `slim = tf.contrib.slim` for TF V2 `import tf_slim as slim`

AttributeError: module 'tensorflow' has no attribute 'contrib'

I am facing this error please help

**Comment by Roxie2003** [comment]
> Replace TF V1 line `slim = tf.contrib.slim` for TF V2 `import tf_slim as slim`

Thank you so muchhhhh :)

**Comment by RubensFPereira** [comment]
Hello Everyone!
You guys can help me with this problem?

  File "F:\Anaconda\envs\pothole\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\builders\dataset_builder.py", line 27, in <module>
    from object_detection.data_decoders import tf_example_decoder
   
   Thanks!
