### ISSUE TITLE
ObjectDetection API not suitable for tf 2.0.0-alpha0

### ISSUE THREAD

**Issue by theangels** [tensorflow/models#6423]
### System information
- **What is the top-level directory of the model you are using**: /Appendix/tensorflow_models/research
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Nope
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 2.0.0-alpha0, and the models lib clone on Mar 11, 2019
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: 10.0
- **GPU model and memory**: 1050Ti
- **Exact command to reproduce**:
PIPELINE_CONFIG_PATH='/home/jovyan/Codelab/model/pipeline.config'
MODEL_DIR='/home/jovyan/Codelab/data'
NUM_TRAIN_STEPS=50000
SAMPLE_1_OF_N_EVAL_EXAMPLES=1
python3 object_detection/model_main.py \
    --pipeline_config_path=${PIPELINE_CONFIG_PATH} \
    --model_dir=${MODEL_DIR} \
    --num_train_steps=${NUM_TRAIN_STEPS} \
    --sample_1_of_n_eval_examples=$SAMPLE_1_OF_N_EVAL_EXAMPLES \
    --alsologtostderr

tf_upgrade_v2 --intree . --outtree . --copyotherfiles False

### Describe the problem
I try to use ObjectDetection API in TensorFlow 2.0.0-alpha0, but the program told me that `AttributeError: module 'tensorflow' has no attribute 'contrib'`, clearly Google has delete the contrlib library. So next step I try to use the `tf_upgrade_v2 utility` to help me converting existing TensorFlow 1.x Python scripts to TensorFlow 2.0. But finally I failed. Here are the message from terminal.

### Source code / logs
![snipaste20190322_205738](https://user-images.githubusercontent.com/11308780/54824185-25fbee00-4ce5-11e9-8646-aa9fcc850387.png)

@wangtz

**Comment by rootkitchao** [comment]
The current version of the object detection API requires Tensorflow 1.X (>1.12).Because the current version requires contrib.slim, which was removed in Tensorflow 2.0.

**Comment by JoseGnRLuis** [comment]
> The current version of the object detection API requires Tensorflow 1.X (>1.12).Because the current version requires contrib.slim, which was removed in Tensorflow 2.0.

Is there any date or plan in the future to migrate it to 2.0?

**Comment by rootkitchao** [comment]
I don't know the specific situation.But the object detection API will be updated to Tensorflow 2.0.

**Comment by theangels** [comment]
> I don't know the specific situation.But the object detection API will be updated to Tensorflow 2.0.

Oh yeah! Thanks a lot.

**Comment by austinmw** [comment]
@rootkitchao Just curious, any idea of what a timeline for that would be?

**Comment by omerrciftcii** [comment]
> @rootkitchao Any idea what the timeline for that is? Just curious, I know it will likely require a lot of work.

did you find something?  I cant use train.py, it still giving this error: 
"AttributeError: module 'tensorflow' has no attribute 'contrib'   "

I tried to use model_main.py but nothing changes. I don't know what should I do

**Comment by pkulzc** [comment]
We are collaborating with TF team to migrate to 2.0 now, but this is a huge effort which may take months.

**Comment by Borda** [comment]
Any update on the actual status of migration to TF 2.0? Are there some particular actions/points that the community may be helpful?

**Comment by yanfengliu** [comment]
@omerrciftcii I think your best option right now is to just create a virtual env with tensorflow 1.x

**Comment by jinfagang** [comment]
@pkulzc How's the progress going?

**Comment by pkulzc** [comment]
We've made some progress but are still not ready for full migration or release.

**Comment by andreiionutdamian** [comment]
@pkulzc thank you for the update! 
Maybe some kind of work-around in the mean time?

**Comment by enyangxxx** [comment]
same question due to error: module 'tensorflow' has no attribute 'GraphDef'?

**Comment by JoeSL** [comment]
@pkulzc any updates on the migration status?

**Comment by wAikAp** [comment]
I used model_main.py in TF2.0 with the same problem.
Traceback (most recent call last):
  File "model_main.py", line 26, in <module>
    from object_detection import model_lib
  File "../object_detection/model_lib.py", line 27, in <module>
    from object_detection import eval_util
  File "../object_detection/eval_util.py", line 40, in <module>
    slim = tf.contrib.slim
AttributeError: module 'tensorflow' has no attribute 'contrib'

I tried to use the tf_upgrade_v2 cmd to the eval_util.py and model_main.py its doesn't work. Although I know this behavior is not scientific. 
BTW, any update for object detection in TF2.0?

**Comment by johannesjung** [comment]
> I used model_main.py in TF2.0 with the same problem.
> Traceback (most recent call last):
> File "model_main.py", line 26, in
> from object_detection import model_lib
> File "../object_detection/model_lib.py", line 27, in
> from object_detection import eval_util
> File "../object_detection/eval_util.py", line 40, in
> slim = tf.contrib.slim
> AttributeError: module 'tensorflow' has no attribute 'contrib'
> 
> I tried to use the tf_upgrade_v2 cmd to the eval_util.py and model_main.py its doesn't work. Although I know this behavior is not scientific.
> BTW, any update for object detection in TF2.0?

Until the Object Detection API is updated to TensorFlow 2 simply use TensorFlow 1.15 (`pip install tensorflow==1.15`). It still contains `contrib` and also a complete implementation of the 2.0 API. Using the `compat.v2` module you can already ensure that your code (except for the Object Detection API part of course) will work with 2.0. Check the TensorFlow 1.15 [release notes](https://github.com/tensorflow/tensorflow/releases/tag/v1.15.0) for further information.

**Comment by jpacifico** [comment]
hi, how's the progress going? Is it now possible to use Object Detection API with TF 2.0 ?

**Comment by Borda** [comment]
@jpacifico I guess it is already released... https://github.com/tensorflow/models/releases/tag/v2.0

**Comment by swarupe** [comment]
Object Detection API is not yet released with TF 2.0 I guess

**Comment by jpacifico** [comment]
> Object Detection API is not yet released with TF 2.0 I guess

yes I guess too, still have the same 'contrib' error with TF 2

**Comment by wAikAp** [comment]
As anyone knows any other ways to train the model with TF2.0 for now situation?

**Comment by blissray** [comment]
Until now, It's now available.

**Comment by vikramg1** [comment]
I tried it and it has the same contrib error. Did anyone get it up and running successfully?

**Comment by KaneFury** [comment]
Hey guys.. does anyone know if the object detection API was updated for TF2 and is working fine?

**Comment by SaschaHeyer** [comment]
Hey @pkulzc 

I see this issues is closed is the Object Detection API already updated for TF2?

**Comment by Borda** [comment]
Maybe create a milestone add there issues and PRs which gas to be done before TF2 compatible...

**Comment by sanchit88** [comment]
Is there any update? TF2.0 is still not working and getting the same "AttributeError: tf.contrib" error.

**Comment by vihari1729** [comment]
> while having tf 2.0.0: how to handle "module 'tensorflow' has no attribute 'GraphDef' "?

Currently tf 2.0.0 doesn't support graphdef model. You should either use keras model or saved model

**Comment by Masoud-Ghodrati** [comment]
is there any update on this issue? It's frustrating.
The way I solved my problem was to use google colab, but training a model for long hours using on colab is a pain.

Please give us some update

**Comment by vihari1729** [comment]
> is there any update on this issue? It's frustrating.
> The way I solved my problem was to use google colab, but training a model for long hours using on colab is a pain.
> 
> Please give us some update

@Masoud-Ghodrati Downgrade your tensorflow version to TF 1.x and try running the code. It may work

**Comment by sanchit88** [comment]
@all: I have tried a combination of Tensorflow 1.15 and Tensorflow models v1.13.0. And, both are working fine. Note that it is important you need to checkout v1.13.0 tag when you download models repo!

At the moment, Tensorflow model v2.0 is still not working.

**Comment by manfye** [comment]
yes still not working, frust

**Comment by ljstrnadiii** [comment]
Looks tike there has been some progress:

https://github.com/tensorflow/models/blob/master/research/object_detection/object_detection_tutorial.ipynb

**Comment by dheera** [comment]
It would be actually really awesome to have an object detection API that is completely abstracted from the framework, such that you could use TF 1.x, TF 2.x, or even PyTorch or other framework to supply a model to use. The API shouldn't need to know that it's TensorFlow or some specific version under the hood; the model should be supplied with the relevant bindings to the specific framework and version that the model depends on.

It should in principle take only a simple line change of e.g.
`from object_detection import load_model
model = load_model("some_model_A_that_uses_tensorflow_1_13.model")`
to
`model = load_model("some_model_A_that_uses_tensorflow_2_0.model")`
or
`model = load_model("some_model_B_that_uses_pytorch.model")`
to switch from one model to another, and all the necessary bindings to the necessary frameworks should be described and handled automatically inside the .model file, which can be a fully packaged tarball, similar to an .apk.

Thoughts?

**Comment by vikramg1** [comment]
@dheera , we are building something close to what you stated above for Edge IoT computer vision: https://alwaysai.co/

**Comment by Masoud-Ghodrati** [comment]
> Looks tike there has been some progress:
> 
> https://github.com/tensorflow/models/blob/master/research/object_detection/object_detection_tutorial.ipynb

how?
it works on colab but not locally? have you tried it locally?

**Comment by ljstrnadiii** [comment]
@Masoud-Ghodrati , well, as you can see, it is 2.x with the object_detection api installed. It was also pushed a few days ago. 

Nightly docker build is not working with it for me.

**Comment by Masoud-Ghodrati** [comment]
> @Masoud-Ghodrati , well, as you can see, it is 2.x with the object_detection api installed. It was also pushed a few days ago.
> 
> Nightly docker build is not working with it for me.

Well, I installed the API on 16 Jan and didn't work on my local machine, the tutorial was TF 2.x. So, I can't see anything new.

**Comment by Shoshin23** [comment]
I think the safest option will be to download to tensorflow 1.0. There's still no update for this. :/

**Comment by sreeni5493** [comment]
Any updates?

**Comment by pkulzc** [comment]
Migrating to TF2 includes a number of critical issues:
- rewriting all network with keras since slim is gone
- rewriting training loop estimator which is not recommended in TF2.
- prepare new configs, new scripts, new checkpoints

Finally we have built a few TF2 models and are developing a few more latest models. The release will happen soon. Sorry for the long waiting!

**Comment by atyshka** [comment]
What about fixing all the imports? On current master in 1.15 there are an abundance of warnings about deprecated names that really clog up the terminal and distract from valuable information. Will the Tensorflow 2.0 automatic converter be able to aid with this?

**Comment by Borda** [comment]
FYI, TF 2.2.0 is just out...

**Comment by haimat** [comment]
Hey guys, I am a bit confused ... This issue here on GitHub is closed, but I can't find any notes on an official release of rht Object Detection API for TF2. What is the current status, can we use it with TF2 now? Thanks in advance.

**Comment by atyshka** [comment]
@haimat No, scroll up you'll notice they closed it even though there is still no TF2 support.

**Comment by haimat** [comment]
That's why I am a bit confused. We use TF2 in our company, I can't change this. I was looking for something powerful as *detector2* for *PyTorch*, which can be used on top of TF (but not TF1.x). Are there any plans for a release of this Object Detection API for TF2?

**Comment by atyshka** [comment]
It’s definitely in progress but there’s a lot to do. I haven’t done it myself but your best bet is looking into the backwards compatibility stuff. It is my understanding that you can use tf 1 code in tf 2 using backwards compatible imports. There’s even an automatic conversion tool that will change your code to work with tf 2. I can’t say it’s easy since this repo is large, but that’s probably the simplest way to get things somewhat working in tf 2. It’s definitely better to rewrite things in the tf 2 style, but this might work as a short term fix. Let us know if you get things working!

**Comment by haimat** [comment]
Hmm... That's unfortunate. The *detectron2* framework from Facebook looks really promising, I was hoping to find something similar for TF2. But if there is no such thing (yet), we might be tempted to switch to *detectron2* and *PyTorch*.

**Comment by vinayentc** [comment]
Hi, any update for the tensorflow 2.0 object detection ? thanks

**Comment by wAikAp** [comment]
So, need how long we can use the TF2.0 object detection what do you guys think?

**Comment by alexdwu13** [comment]
@pkulzc Thanks for keeping us updated. Is there an experimental Obj Det branch we can pull from before an official update is released?

**Comment by twdent** [comment]
> We are collaborating with TF team to migrate to 2.0 now, but this is a huge effort which may take months.

@pkulzc thanks for all your assistance. Are there any updates on this? Would be a great 1 year anniversary present for this comment :P

**Comment by davidmurray** [comment]
Also wondering when this will be updated to Tensorflow 2.0! Thanks!

**Comment by deepthiMBapat** [comment]
Hi, Currently,Which version of tf supports training on custom data set using object detection API ?

**Comment by sourangshupal** [comment]
Is there any ongoing progress?

**Comment by Samruilio** [comment]
Thought tensorflow is the tool I need to begin AI study but I can't even run a tutorial code without errors :(

**Comment by haimat** [comment]
Isn't this a real bummer for Google? I mean, there are a few mature object detection frameworks based on PyTorch (e.g. Detectron2, which is a great piece of software btw.), which seem to get more and more attention. Isn't Google risking that more and more people would switch to PyTorch if Google doesn't provide a proper and fully documented (!!) object detection framework for TF2?

**Comment by saberkun** [comment]
@jaeyounkim @pengchongjin

**Comment by hafiz031** [comment]
> > Looks tike there has been some progress:
> > https://github.com/tensorflow/models/blob/master/research/object_detection/object_detection_tutorial.ipynb
> 
> how?
> it works on colab but not locally? have you tried it locally?

They have also provided instruction for local installation in the same page. It might be helpful. You may check out it or can directly go from here: [installation instructions](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md)

**Comment by RAZOR15000** [comment]
so, there is no way to train a new model with any version of tensorflow?  is that it ??

**Comment by vijay0523** [comment]
It's been a few months now... Is there any update ? For contrib support in TF2>=2?

**Comment by vijay0523** [comment]
Also I cannot downgrade TF to any of the lower versions as pip shows only versions available are 2.2 , 2.2a, latest ones

**Comment by codecolony** [comment]
+1 subscriber to TF 2.0+ Object Detection API status.

**Comment by nickkimer** [comment]
sad day as I have now no choice but to return to pyTorch :(

**Comment by enragedginger** [comment]
@nickkimer Same here. I'm now porting everything off of Tensorflow.

**Comment by haimat** [comment]
I would really be interested to know what Google "officially" thinks and plans about htis matter. Aren't they a bit afraid that with every week while nothing happens in this matter more and more users switch to PyTorch (or GluonCV or something else)?

**Comment by Zeldon** [comment]
Hi guys, any news of this migration?

**Comment by jarviscodes** [comment]
> 
> 
> Also I cannot downgrade TF to any of the lower versions as pip shows only versions available are 2.2 , 2.2a, latest ones

That's very likely because you are on python 3.8 and tf==1.15 does not support 3.8. You'll need an environment with python 3.7.6 and this should work.

**Comment by yaysummeriscoming** [comment]
Also worth noting that it's now possible to set the colab TPU tensorflow version. This means you can continue to use tensorflow 1.15 & OD API in colab:

```
!pip uninstall -y tensorflow
!pip install tensorflow==1.15.2

# Restart runtime here, then run:

!pip install cloud-tpu-client
from cloud_tpu_client import Client

# Check that TF version is 1.15.2
print("Tensorflow version: ", tf.__version__)

c = Client()
c.configure_tpu_version(tf.__version__, restart_type='ifNeeded')
```

**Comment by vinayentc** [comment]
TensorFlow Object Detection API supports both TensorFlow 2 (TF2) and TensorFlow 1 (TF1) officially now.

 https://github.com/tensorflow/models/tree/master/research/object_detection

**Comment by novoforce** [comment]
Could anyone help me how to use eval_utils.py for evaluation of the training and get the mAP mIOU scores.
