### ISSUE TITLE
hparams = contrib_training.HParams( NameError: name 'contrib_training' is not defined

### ISSUE THREAD

**Issue by agnieszkajust** [tensorflow/models#9298]
https://github.com/tensorflow/models/tree/r2.3.0/research/object_detection

Describe:

After run: python model_main_tf2.py --model_dir=$MODEL_DIR --num_train_steps=$NUM_TRAIN_STEPS --sample_1_of_n_eval_examples=$SAMPLE_1_OF_N_EVAL_EXAMPLES --pipeline_config_path=$PIPELINE_CONFIG_PATH --alsologtostderr 
I got: hparams = contrib_training.HParams(
NameError: name 'contrib_training' is not defined

 System information:

- Ubuntu 20.04
- TensorFlow installed by: pip install tensorflow
- TensorFlow version (use command below):tensorflow 2.3.0
- Python version: 3.8.2
- GCC/Compiler version: gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0
- CUDA/cuDNN version: CUDA Version: 11.0 , cudnn 7.6.5
- GPU model and memory: GeForce RTX 2060

**Comment by Harirai** [comment]
Hi I'm new to TensorFlow community, can anyone guide me how to approach/get started with issues like this?
(I tried to replicate it but I'm getting a different error)
Thanks in advance! :)
![Screenshot from 2020-09-25 23-46-56](https://user-images.githubusercontent.com/43855822/94302229-85e1ed80-ff89-11ea-80eb-6a18a6c8218c.png)

**Comment by agnieszkajust** [comment]
go to the research directory and type:

export PYTHONPATH=$PYTHONPATH:pwd:pwd/slim

**Comment by Harirai** [comment]
Hi, @agnieszkajust  thanks for helping me, now it is showing `cannot import 'model_lib_v2'` .
I tried to fix that by running 
```
python setup.py build 
python setup.py install
```
but it wasn't working. 
I printed the contents of the `object_detection` package, `model_lib_v2` was not present in it.
Can you please suggest what should I do?  

![Screenshot from 2020-09-28 23-02-38](https://user-images.githubusercontent.com/43855822/94466350-ecac1480-01de-11eb-8774-025d580129b0.png)

**Comment by agnieszkajust** [comment]
What version of tensorflow and which branch 'tensorflow/models'  do you have?

**Comment by Harirai** [comment]
I have Tensorflow 2.3.0 and working on the `r2.3.0` branch of "tensorflow/models".
After reinstalling above errors didn't occur.
But now I'm getting

    Traceback (most recent call last):  
      File "model_main_tf2.py", line 112, in <module>  
        tf.app.run()  
    AttributeError: module 'tensorflow.compat.v2' has no attribute 'app'

Tf2 doesnt have attribute "app", do I have to change it to ` tf.compat.v1.app.run()`, why this change is not merged into branch r2.3.0 ?

**Comment by agnieszkajust** [comment]
I don't know, but I also changed to tf.compat.v1.app.run().

**Comment by Zrufy** [comment]
@agnieszkajust how do you solve the problem of `name 'contrib_training' is not defined`

**Comment by agnieszkajust** [comment]
I don't solve it.

**Comment by advaza** [comment]
My workaround in `utils/autoaugment_utils.py` :

```python
from tensorflow_addons import image as contrib_image
from collections import namedtuple
# pylint: disable=g-import-not-at-top
# try:
#   from tensorflow.contrib import image as contrib_image
#   from tensorflow.contrib import training as contrib_training
# except ImportError:
#   # TF 2.0 doesn't ship with contrib.
#   pass
# pylint: enable=g-import-not-at-top

...

def hparams(**kwargs):
    return namedtuple("HParams", kwargs.keys())(*kwargs.values())

  # Line 1670
  augmentation_hparams = hparams(
      cutout_max_pad_fraction=0.75,
      cutout_bbox_replace_with_mean=False,
      cutout_const=100,
      translate_const=250,
      cutout_bbox_const=50,
      translate_bbox_const=120)
```

**Comment by shreyas-afk** [comment]
> My workaround in `utils/autoaugment_utils.py` :
> 
> ```python
> from tensorflow_addons import image as contrib_image
> from collections import namedtuple
> # pylint: disable=g-import-not-at-top
> # try:
> #   from tensorflow.contrib import image as contrib_image
> #   from tensorflow.contrib import training as contrib_training
> # except ImportError:
> #   # TF 2.0 doesn't ship with contrib.
> #   pass
> # pylint: enable=g-import-not-at-top
> 
> ...
> 
> def hparams(**kwargs):
>     return namedtuple("HParams", kwargs.keys())(*kwargs.values())
> 
>   # Line 1670
>   augmentation_hparams = hparams(
>       cutout_max_pad_fraction=0.75,
>       cutout_bbox_replace_with_mean=False,
>       cutout_const=100,
>       translate_const=250,
>       cutout_bbox_const=50,
>       translate_bbox_const=120)
> ```

sadly this is not working now

https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md, they partially moved some of the components i guess. did you install tensorflow_addons seperately ?

had to downgrade my tf from 2.5.0 to <1.3.1 to get it working
