### ISSUE TITLE
AttributeError: module 'tensorflow.contrib' has no attribute 'distribute'

### ISSUE THREAD

**Issue by baiyujian082** [tensorflow/models#5983]
I was using tf 1.4 and run 'sh run_deep_speech_new.sh',  could any one tell me why I meet the error below:

Traceback (most recent call last):
  File "deep_speech.py", line 410, in <module>
    absl_app.run(main)
  File "/usr/local/lib/python3.6/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "deep_speech.py", line 403, in main
    run_deep_speech(flags_obj)
  File "deep_speech.py", line 226, in run_deep_speech
    distribution_strategy = distribution_utils.get_distribution_strategy(num_gpus)
  File "/home/private/zjx/models-master/official/utils/misc/distribution_utils.py", line 40, in get_distribution_strategy
    return tf.contrib.distribute.OneDeviceStrategy("device:GPU:0")
  File "/usr/local/lib/python3.6/lib/python3.6/site-packages/tensorflow/python/util/lazy_loader.py", line 54, in __getattr__
    return getattr(module, item)
AttributeError: module 'tensorflow.contrib' has no attribute 'distribute'

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by baiyujian082** [comment]
> 
> 
> Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
> What is the top-level directory of the model you are using
> Have I written custom code
> OS Platform and Distribution
> TensorFlow installed from
> TensorFlow version
> Bazel version
> CUDA/cuDNN version
> GPU model and memory
> Exact command to reproduce

It works on tf1.9,I think this  is caused by tf version
