### ISSUE TITLE
AttributeError: 'module' object has no attribute 'DEFINE_enum'

### ISSUE THREAD

**Issue by jiyongma** [tensorflow/models#3925]
Traceback (most recent call last):
  File "deeplab/model_test.py", line 20, in <module>
    from deeplab import common
  File "/home/m/models/research/deeplab/common.py", line 45, in <module>
    flags.DEFINE_enum('model_variant', 'mobilenet_v2',
AttributeError: 'module' object has no attribute 'DEFINE_enum'

**Comment by bitfort** [comment]
Thanks for reaching out, can you include information about whcih version of TF you are using and the system setup?

**Comment by jiyongma** [comment]
Thank you. I have solved this problem. The reason is that tensorflow didn't upgrade. It was originally 1.2.. When I upgraded to 1.6, I solved it.

**Comment by bitfort** [comment]
Glad to hear it is working.
