### ISSUE TITLE
cannot import name 'anchor_generator_pb2'

### ISSUE THREAD

**Issue by urvashibhavsar** [tensorflow/models#1962]
I have tensorflow-gpu installed in a container. I downloaded models in the tensorflow directory and installed protos 3.3. i tried to execute the last command in the installation section
python object_detection/builders/model_builder_test.py
but it gives me the following error:
"ImportError: cannot import name 'anchor_generator_pb2' "
how to fix this?

**Comment by Sophia-intel** [comment]
I have met the same problems in testing the installing, have you fixed it?

**Comment by Jennyidream0318** [comment]
u need to transform xxx.proto file into xxx_pb2.py file by using"protoc -I=./ --python_out=./ xxx.proto".
But some of the "xxx.proto" file here also have some trouble, u can try this way at first.

**Comment by urvashibhavsar** [comment]
i tried that, it gives me the following error even when i use the absolute path
anchor_generator.proto: Import "/usr/local/lib/python3.4/dist-packages/tensorflow/models/object_detection/protos/grid_anchor_generator.proto" was not found or had errors.
anchor_generator.proto: Import "/usr/local/lib/python3.4/dist-packages/tensorflow/models/object_detection/protos/ssd_anchor_generator.proto" was not found or had errors.
anchor_generator.proto:15:5: "GridAnchorGenerator" is not defined.
anchor_generator.proto:16:5: "SsdAnchorGenerator" is not defined.

**Comment by Jennyidream0318** [comment]
because all the proto files in ./object_detection/protos should be transformed into python files, i didn't do that successfully yet.

**Comment by urvashibhavsar** [comment]
I followed the commands given in the installation guide using tensorflow 1.2, and it worked. I did not find a way to make it work with tensorflow 1.0 though.

**Comment by louiseruiwenli** [comment]
The path of grid_anchor_generator.proto and ssd_anchor_generator.proto when you import them in anchor_generator.proto may not be correct. If they are in the same folder, try deleting "object_detection/protos" when you import them. I tried and it worked.

**Comment by xmaj2008** [comment]
locate at dir : /models/
run in command:
protoc -I=./ --python_out=./  .\object_detection\protos\*.proto

all of mine:
(C:\Program Files\Anaconda3) C:\Program Files\Anaconda3\Lib\site-packages\tensor
flow\models>protoc -I=./ --python_out=./ .\object_detection\protos\*.proto

**Comment by xmaj2008** [comment]
locate at dir : /models/
run in command:
protoc -I=./ --python_out=./ .\object_detection\protos\*.proto

all of mine:
(C:\Program Files\Anaconda3) C:\Program Files\Anaconda3\Lib\site-packages\tensor
flow\models>protoc -I=./ --python_out=./ .\object_detection\protos\*.proto

**Comment by xmaj2008** [comment]
locate at dir : /models/
run in command:
protoc -I=./ --python_out=./ .\object_detection\protos\\*.proto

all of mine:
(C:\Program Files\Anaconda3) C:\Program Files\Anaconda3\Lib\site-packages\tensor
flow\models>protoc -I=./ --python_out=./ .\object_detection\protos\\*.proto

**Comment by louiseruiwenli** [comment]
Could you show me what's in the import section of anchor_generator.proto file? Thanks. 

The original one is:
//import "object_detection/protos/grid_anchor_generator.proto";
//import "object_detection/protos/ssd_anchor_generator.proto";

And I changed it to:
import "grid_anchor_generator.proto";
import "ssd_anchor_generator.proto";

**Comment by dat-ai** [comment]
I ran into the same error. 

Steps to resolve:
1. Read the (`installation`)[https://github.com/tensorflow/models/blob/master/object_detection/g3doc/installation.md] instruction. 
2. Before executing `model_builder_test.py`,  you need to compile proto files as following:
```
# From tensorflow/models/
protoc object_detection/protos/*.proto --python_out=.
```

**Comment by mickeybao** [comment]
I have open file ‘anchor_generator.proto’ and find the reason。
in line 5 
import "object_detection/protos/grid_anchor_generator.proto";
so ,we should run command "protoc *.proto --python_out=." in the parent path of"object_detection " ,just like this "protoc object_detection/protos/*.proto --python_out=."

**Comment by navinkeshava** [comment]
in object_detection protos folder the import line is given
import "object_detection/protos/grid_anchor_generator.proto";

change that to 
import "research/object_detection/protos/grid_anchor_generator.proto";

**Comment by k4r3l** [comment]
Not a single "solution" has worked so far. Getting tired of trying everything without prevail. This takes way too much time!

Dowloaded protobuf v3.4 for windows: https://github.com/google/protobuf/releases/tag/v3.4.0
Placed protoc.exe in "research" folder
Within "research" folder ran:
>> protoc object_detection/protos/.proto --python_out=. 
>> gives no error
 
Run python object_detection/builders/model_builder_test.py:
>>from object_detection.protos import anchor_generator_pb2
>>ImportError: cannot import name 'anchor_generator_pb2'

anchor_generator_pb2.py file is located in object_detection/protos

Have tried @navinkeshava's recommendation. Have tried different protobuf versions....
Nothing works!!
Please help!!!!

**Comment by lekshmi17** [comment]
Add the following code instead of the line... from object-detection.protos import anchor_generator_pb2
//
import sys
sys.path.insert(0,"C:/Users/user/AppData/Local/Programs/Python/Python36/models/research/object_detection/protos")
import anchor_generator_pb2
//

Just change the path to the respective location on your computer

**Comment by k4r3l** [comment]
Hi lekshmi17, 

thank you for your reply. Unfortunately, that does not change one bit. The solution you propose does not feel quite robust to be honest. Changing all relative paths in all files makes things so messy.

This is what I get after modifying anchor_generator_builder.py according to your suggestion. I added the path but nothing changed. So I changed the path with os.chdir() to .C:/.../research/models/object_detection/protos

>>>
C:\PythonEnv\WinPython\3.6.1.0\tensorflow\models\research>python object_detection/builders/model_builder_test.py
C:\PythonEnv\WinPython\3.6.1.0\python-3.6.1.amd64\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 21, in <module>
    from object_detection.builders import model_builder
  File "C:\PythonEnv\WinPython\3.6.1.0\python-3.6.1.amd64\lib\site-packages\slim-0.1-py3.6.egg\object_detection\builders\model_builder.py", line 17, in <module>
    from object_detection.builders import anchor_generator_builder
  File "C:\PythonEnv\WinPython\3.6.1.0\python-3.6.1.amd64\lib\site-packages\slim-0.1-py3.6.egg\object_detection\builders\anchor_generator_builder.py", line 30, in <module>
    import anchor_generator_pb2
ModuleNotFoundError: No module named 'anchor_generator_pb2'

Can you make sense of this?

Much appreciated for your time and effort!

**Comment by kpierce8** [comment]
Does anyone know if this works on windows at all? I'm stuck at the same place.

**Comment by kutvonenaki** [comment]
Also wondering if it's less trouble to install Ubuntu than to try to make this work on Windows :) Stuck in the same place as well.

**Comment by kpierce8** [comment]
Honestly I’ve spent many days going down endless rabbit holes as I continue to try and get this running on Ubuntu. I don’t understand how anyone gets anything to work on Linux. I know millions of people do, but I’m finding myself blindly fumbling all over the internet. Deep Learning seems super simple compared to building Tensorflow from source.

**Comment by ebimor** [comment]
If you're in linux 14, first follow this thread and add protoc3_3 to you tensorflow 

https://github.com/tensorflow/models/issues/1834

and then if you're still getting the error run something like

/home/ebrahim/tensorflow/protoc_3.3/bin/protoc  -I=./ --python_out=./ .\object_detection\protos\*.proto

**Comment by neomarian** [comment]
I fixed this issue by running 
`python setup.py install` in 'tensorflow\models\research' BEFORE to run `python object_detection/builders/model_builder_test.py`.
In that way all py files are copied from 'tensorflow\models\research' to 'C:\Users\user\AppData\Local\Programs\Python\Python36\Lib\site-packages\object_detection-0.1-py3.6.egg\object_detection'

**Comment by Paulswith** [comment]
it's working for me:
you should be on the `Tensorflow/models/research` to execute, like this:

![image](https://user-images.githubusercontent.com/24262233/41763119-c06eaee2-762f-11e8-92b2-db4b0cfd96c0.png)

hope can help yous.

**Comment by mangalbhaskar** [comment]
This worked for me. From the path: `models/research`, executed following:
```bash
protoc -I=./ --python_out=./ ./object_detection/protos/*.proto
export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim
# Test
python object_detection/builders/model_builder_test.py
```
I'm using TF 1.9.0 on Ubuntu 18.04

**Comment by xiaofansong** [comment]
"python setup.py install in 'tensorflow\models\research' BEFORE to run python object_detection/builders/model_builder_test.py. " WORKS TO ME! thanks @neomarian

**Comment by NguyenHoang1996** [comment]
Thanks @mangalbhaskar, that worked for me :+1:

**Comment by LalitPradhan** [comment]
> This worked for me. From the path: `models/research`, executed following:
> 
> ```shell
> protoc -I=./ --python_out=./ ./object_detection/protos/*.proto
> export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim
> # Test
> python object_detection/builders/model_builder_test.py
> ```
> 
> I'm using TF 1.9.0 on Ubuntu 18.04

This helped. I was trying to run it on an ARM. Thanks a lot @mangalbhaskar

**Comment by pcheng2** [comment]
> 
> 
> I fixed this issue on WINDOWS by running
> `python setup.py install` in 'tensorflow\models\research' BEFORE to run `python object_detection/builders/model_builder_test.py`.
> In that way all py files are copied from 'tensorflow\models\research' to 'C:\Users\user\AppData\Local\Programs\Python\Python36\Lib\site-packages\object_detection-0.1-py3.6.egg\object_detection'

It works for me. Thank you so much!

**Comment by Rajamohanreddyai** [comment]
hi,
check this one, run the below command from research path
you can do manually

# From tensorflow/models/research/
 export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim

protoc --python_out=. .\object_detection\protos\calibration.proto
protoc --python_out=. .\object_detection\protos\anchor_generator.proto

and verify below video
https://youtu.be/nZUxoHPFf4

**Comment by sahilshaikh89** [comment]
If its windows, try adding below paths in PYTHONPATH
<tensorflow_model_dirPath>\research;<tensorflow_model_dirPath>\research\slim;<tensorflow_model_dirPath>\research\object_detection

That worked out for me.

**Comment by Iorek73** [comment]
Can I not just download the .py files instead of going through this?

**Comment by senthurRam33** [comment]
@mangalbhaskar Your solution worked for me. Thanks for that

**Comment by sandeep22-v** [comment]
> Hi lekshmi17,
> 
> thank you for your reply. Unfortunately, that does not change one bit. The solution you propose does not feel quite robust to be honest. Changing all relative paths in all files makes things so messy.
> 
> This is what I get after modifying anchor_generator_builder.py according to your suggestion. I added the path but nothing changed. So I changed the path with os.chdir() to .C:/.../research/models/object_detection/protos
> 
> > > >
> 
> C:\PythonEnv\WinPython\3.6.1.0\tensorflow\models\research>python object_detection/builders/model_builder_test.py
> C:\PythonEnv\WinPython\3.6.1.0\python-3.6.1.amd64\lib\site-packages\h5py__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
> from ._conv import register_converters as _register_converters
> Traceback (most recent call last):
> File "object_detection/builders/model_builder_test.py", line 21, in
> from object_detection.builders import model_builder
> File "C:\PythonEnv\WinPython\3.6.1.0\python-3.6.1.amd64\lib\site-packages\slim-0.1-py3.6.egg\object_detection\builders\model_builder.py", line 17, in
> from object_detection.builders import anchor_generator_builder
> File "C:\PythonEnv\WinPython\3.6.1.0\python-3.6.1.amd64\lib\site-packages\slim-0.1-py3.6.egg\object_detection\builders\anchor_generator_builder.py", line 30, in
> import anchor_generator_pb2
> ModuleNotFoundError: No module named 'anchor_generator_pb2'
> 
> Can you make sense of this?
> 
> Much appreciated for your time and effort!

same error for me as well

**Comment by wahajahmad** [comment]
If you are having following warning while executing first command (_protoc object_detection/protos/*.proto --python_out=._) 
```
object_detection/protos/calibration.proto:41:3: Expected "required", "optional", or "repeated".
object_detection/protos/calibration.proto:41:6: Expected field name.
object_detection/protos/calibration.proto:53:3: Expected "required", "optional", or "repeated".
object_detection/protos/calibration.proto:53:6: Expected field name.
```

Follow the solution below: (credits [Humayun](https://github.com/tensorflow/models/issues/1834#issuecomment-312476609))

You need to download protoc version 3.3 (already compiled). Used protoc inside bin directory to run this command like this:
```
tensorflow$ mkdir protoc_3.3
tensorflow$ cd protoc_3.3
tensorflow/protoc_3.3$ wget wget https://github.com/google/protobuf/releases/download/v3.3.0/protoc-3.3.0-linux-x86_64.zip
tensorflow/protoc_3.3$ chmod 775 protoc-3.3.0-linux-x86_64.zip
tensorflow/protoc_3.3$ unzip protoc-3.3.0-linux-x86_64.zip
tensorflow/protoc_3.3$ cd ../models/
tensorflow/protoc_3.3$ /home/humayun/tensorflow/protoc_3.3/bin/protoc object_detection/protos/*.proto --python_out=.
```

**Comment by MichaelSeitz98** [comment]
Hey guy, 

I am trying to install the tfod api on linux. I did convert the protos-files to .py files via
`protoc object_detection/protos/*.proto --python_out=.`

However, I still get the same error message after compiling the protos files. 

`(tfod) [username research]$ python object_detection/builders/model_builder_tf2_test.py`
`2021-07-22 09:38:07.654347: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
Traceback (most recent call last):
  File "object_detection/builders/model_builder_tf2_test.py", line 25, in <module>
    from object_detection.builders import model_builder
  File "/opt/bwhpc/common/jupyter/tensorflow/2021-07-05/lib/python3.6/site-packages/object_detection/builders/model_builder.py", line 23, in <module>
    from object_detection.builders import anchor_generator_builder
  File "/opt/bwhpc/common/jupyter/tensorflow/2021-07-05/lib/python3.6/site-packages/object_detection/builders/anchor_generator_builder.py", line 27, in <module>
    from object_detection.protos import anchor_generator_pb2
ImportError: cannot import name 'anchor_generator_pb2'
(tfod) [username research]$
`
Can anyone help me has anyone now solved this problem? 

Thank you very much! 
Michael

**Comment by hozjan** [comment]
> I tried the following solution above with no luck. Everything I try to do is keeps on giving me the same error message. `ImportError: cannot import name 'anchor_generator_pb2' from 'object_detection.protos' (C:\PythonProjects\ObjectDetectionTake3\models\research\object_detection\protos\__init__.py)`

Adding "from object_detection.protos" in front of every faulthy import solved the issue for me. Altho there is a clear warning DO NOT EDIT I don't think this changes any core functions of the file.
