### ISSUE TITLE
AttributeError: module 'keras.api._v2.keras.optimizers' has no attribute 'experimental'

### ISSUE THREAD

**Issue by NasrYousif** [tensorflow/models#10525]
When I want to run my model in colab using this piece of code. 
```
!python model_main_tf2.py --model_dir=models/ssd_mobilenet_v2_fpnlite_640x640_coco17_tpu-8 --pipeline_config_path=models/ssd_mobilenet_v2_fpnlite_640x640_coco17_tpu-8/pipeline.config
# !python model_main_tf2.py --model_dir=models/[name_of_pre-trained-model_you_downloaded] --pipeline_config_path=models/[name_of_pre-trained-model_you_downloaded]/pipeline.config
```
This error is flagged 
Error:

Traceback (most recent call last):
  File "model_main_tf2.py", line 32, in <module>
    from object_detection import model_lib_v2
  File "/usr/local/lib/python3.7/dist-packages/object_detection/model_lib_v2.py", line 31, in <module>
    from object_detection import model_lib
  File "/usr/local/lib/python3.7/dist-packages/object_detection/model_lib.py", line 34, in <module>
    from object_detection.builders import optimizer_builder
  File "/usr/local/lib/python3.7/dist-packages/object_detection/builders/optimizer_builder.py", line 25, in <module>
    from official.modeling.optimization import ema_optimizer
  File "/content/gdrive/My Drive/Tensorflow/models/official/modeling/optimization/__init__.py", line 23, in <module>
    from official.modeling.optimization.optimizer_factory import OptimizerFactory
  File "/content/gdrive/My Drive/Tensorflow/models/official/modeling/optimization/optimizer_factory.py", line 31, in <module>
    'sgd_experimental': tf.keras.optimizers.experimental.SGD,
AttributeError: module 'keras.api._v2.keras.optimizers' has no attribute 'experimental'

**Comment by NasrYousif** [comment]
I have follow this path File "/content/gdrive/My Drive/Tensorflow/models/official/modeling/optimization/optimizer_factory.py"

and edit two line of code, 31, 33
from 
`'sgd_experimental': tf.keras.optimizers.experimental.SGD,`
`'adam_experimental': tf.keras.optimizers.experimental.Adam,`

to 

`'sgd_experimental': tf.keras.optimizers.SGD,`
`'adam_experimental': tf.keras.optimizers.Adam,`

and work well

**Comment by gadagashwini** [comment]
@NasrYousif,
```
tf.keras.optimizers.experimental.SGD() 
tf.keras.optimizers.experimental.Adam() 
```

These APIs are new and only available via `pip install tf-nightly.`
Please take look at https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/experimental/Adam

`tf.keras.optimizers.SGD` and `tf.keras.optimizers.Adam` works on stable Tensorflow version ~2.8.

**Comment by Bmg09** [comment]
tensorflow 2.9 fixed it
