### ISSUE TITLE
models not works on TF 1.8.0 because of tf.contrib.data module has been deprecated

### ISSUE THREAD

**Issue by kuilef** [tensorflow/models#5136]
### System information
- **What is the top-level directory of the model you are using**: d:\Documents\GitHub\models 
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 64 bit
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.8.0
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: 9.0
- **GPU model and memory**: 1080 Ti
- **Exact command to reproduce**: cd models/official/mnist  python mnist.py

### Describe the problem
running mnist.py script gives an error
AttributeError: module 'tensorflow.contrib.data' has no attribute 'TFRecordDataset'
which can be solved changing strings 70 and 77 as written in https://github.com/tensorflow/tensorflow/blob/r1.4/tensorflow/contrib/data/README.md
Same thing with other models.

### Source code / logs
not working code:
```
  dataset = tf.contrib.data.TFRecordDataset([tfrecords_file])

  # For training, repeat the dataset forever
  if mode == tf.estimator.ModeKeys.TRAIN:
    dataset = dataset.repeat()

  # Map the parser over dataset, and batch results by up to batch_size
  dataset = dataset.map(parser, num_threads=1, output_buffer_size=batch_size)
```
working code:
```
  dataset = tf.data.TFRecordDataset([tfrecords_file])

  # For training, repeat the dataset forever
  if mode == tf.estimator.ModeKeys.TRAIN:
    dataset = dataset.repeat()

  # Map the parser over dataset, and batch results by up to batch_size
  dataset = dataset.map(parser, num_parallel_calls=1).prefetch(batch_size)
```

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
