### ISSUE TITLE
Error running translate.py - 'module' object has no attribute 'GRUCell'

### ISSUE THREAD

**Issue by lixzhang** [tensorflow/models#853]
I got the following error while running translate.py

python translate.py --data_dir /datadrive/tensorflow/Data/SSM/
Preparing WMT data in /datadrive/tensorflow/Data/SSM/
Creating 3 layers of 1024 units.
Traceback (most recent call last):
  File "translate.py", line 297, in <module>
    tf.app.run()
  File "/home/user/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "translate.py", line 294, in main
    train()
  File "translate.py", line 153, in train
    model = create_model(sess, False)
  File "translate.py", line 132, in create_model
    dtype=dtype)
  File "/datadrive/tensorflow/GitDownload/models/tutorials/rnn/translate/seq2seq_model.py", line 122, in __init__
    single_cell = tf.contrib.rnn.GRUCell(size)
AttributeError: 'module' object has no attribute 'GRUCell'

**Comment by nealwu** [comment]
I would suggest [installing TensorFlow from source](https://www.tensorflow.org/get_started/os_setup#installing_from_sources) using the current master version and trying again.

**Comment by Kangmo** [comment]
I hit the same issue even after installing TensorFlow from source with version v0.12.1

I had to change the following lines, but having a new issue.

```
kagnmo@kagnmo-ubuntu:~/ml/models/tutorials/rnn/translate$ git diff HEAD
diff --git a/tutorials/rnn/translate/seq2seq_model.py b/tutorials/rnn/translate/seq2seq_model.py
index cdc04ad..16fb249 100644
--- a/tutorials/rnn/translate/seq2seq_model.py
+++ b/tutorials/rnn/translate/seq2seq_model.py
@@ -119,16 +119,16 @@ class Seq2SeqModel(object):
       softmax_loss_function = sampled_loss
 
     # Create the internal multi-layer cell for our RNN.
-    single_cell = tf.contrib.rnn.GRUCell(size)
+    single_cell = tf.nn.rnn_cell.GRUCell(size)
     if use_lstm:
-      single_cell = tf.contrib.rnn.BasicLSTMCell(size)
+      single_cell = tf.nn.rnn_cell.BasicLSTMCell(size)
     cell = single_cell
     if num_layers > 1:
-      cell = tf.contrib.rnn.MultiRNNCell([single_cell] * num_layers)
+      cell = tf.nn.rnn_cell.MultiRNNCell([single_cell] * num_layers)
 
     # The seq2seq function: we use embedding for the input and attention.
     def seq2seq_f(encoder_inputs, decoder_inputs, do_decode):
-      return tf.contrib.legacy_seq2seq.embedding_attention_seq2seq(
+      return tf.nn.seq2seq.embedding_attention_seq2seq(
           encoder_inputs,
           decoder_inputs,
           cell,
@@ -158,7 +158,7 @@ class Seq2SeqModel(object):
 
     # Training outputs and losses.
     if forward_only:
-      self.outputs, self.losses = tf.contrib.legacy_seq2seq.model_with_buckets(
+      self.outputs, self.losses = tf.nn.seq2seq.model_with_buckets(
           self.encoder_inputs, self.decoder_inputs, targets,
           self.target_weights, buckets, lambda x, y: seq2seq_f(x, y, True),
           softmax_loss_function=softmax_loss_function)
@@ -170,7 +170,7 @@ class Seq2SeqModel(object):
               for output in self.outputs[b]
           ]
     else:
-      self.outputs, self.losses = tf.contrib.legacy_seq2seq.model_with_buckets(
+      self.outputs, self.losses = tf.nn.seq2seq.model_with_buckets(
           self.encoder_inputs, self.decoder_inputs, targets,
           self.target_weights, buckets,
           lambda x, y: seq2seq_f(x, y, False),

```

New issue : 
```
$ python translate.py --data_dir ~/ml/WMT15Website/
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
Preparing WMT data in /home/kagnmo/ml/WMT15Website/
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: GeForce GTX 1080
major: 6 minor: 1 memoryClockRate (GHz) 1.835
pciBusID 0000:0a:00.0
Total memory: 7.92GiB
Free memory: 7.60GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080, pci bus id: 0000:0a:00.0)
Creating 3 layers of 1024 units.
Traceback (most recent call last):
  File "translate.py", line 297, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "translate.py", line 294, in main
    train()
  File "translate.py", line 153, in train
    model = create_model(sess, False)
  File "translate.py", line 132, in create_model
    dtype=dtype)
  File "/home/kagnmo/ml/models/tutorials/rnn/translate/seq2seq_model.py", line 177, in __init__
    softmax_loss_function=softmax_loss_function)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/seq2seq.py", line 1130, in model_with_buckets
    softmax_loss_function=softmax_loss_function))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/seq2seq.py", line 1058, in sequence_loss
    softmax_loss_function=softmax_loss_function))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/seq2seq.py", line 1022, in sequence_loss_by_example
    crossent = softmax_loss_function(logit, target)
  File "/home/kagnmo/ml/models/tutorials/rnn/translate/seq2seq_model.py", line 117, in sampled_loss
    num_classes=self.target_vocab_size),
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn.py", line 1412, in sampled_softmax_loss
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn.py", line 1219, in _compute_sampled_logits
    inputs, sampled_w, transpose_b=True) + sampled_b
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/math_ops.py", line 1729, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 1442, in _mat_mul
    transpose_b=transpose_b, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 759, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2242, in create_op
    set_shapes_for_outputs(ret)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1617, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1568, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 675, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Shape must be rank 2 but is rank 1 for 'model_with_buckets/sequence_loss/sequence_loss_by_example/sampled_softmax_loss/MatMul_1' (op: 'MatMul') with input shapes: [?], [?,1024].

```

**Comment by lixzhang** [comment]
Here's to confirm that the program ran successfully by installing from source, as recommended by @nealwu.

**Comment by michaelisard** [comment]
Closing now, but please reopen if the problem isn't fixed.

**Comment by nealwu** [comment]
@lixzhang Unfortunately the model will not be modified so that previous versions of TensorFlow will work with it. However you should expect that installing from source or potentially also using the [nightly builds](https://github.com/tensorflow/tensorflow#installation) should get it working.

**Comment by lixzhang** [comment]
@nealwu Keeping the model as is makes sense. I was wondering if the other ways of install - [Pip install](https://www.tensorflow.org/get_started/os_setup#pip_installation), [Anaconda install](https://www.tensorflow.org/get_started/os_setup#anaconda_installation), etc - will be updated so that they support the program "translate.py". It seems something in the master branch is missing in these other ways of installation. Anyways, thanks for the pointers on [Installing from sources](https://www.tensorflow.org/get_started/os_setup#installing_from_sources) that allowed me to run the code.

**Comment by nealwu** [comment]
Those should all be updated eventually with the next release of TensorFlow. For now, installing from source or from nightly binaries should do the trick.

Thanks for sending this in!

**Comment by asispatra** [comment]
Hi @nealwu ,
I am working on TensorFlow 0.12.0 and still seeing the issue.
```
$ python translate.py --data_dir /HOME/WMT15
Preparing WMT data in /HOME/WMT15
Creating 3 layers of 1024 units.
Traceback (most recent call last):
  File "translate.py", line 297, in <module>
    tf.app.run()
  File "/opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "translate.py", line 294, in main
    train()
  File "translate.py", line 153, in train
    model = create_model(sess, False)
  File "translate.py", line 132, in create_model
    dtype=dtype)
  File "/mldl/NVME/scratch/asis/mldl/seq2seq/models/tutorials/rnn/translate/seq2seq_model.py", line 122, in __init__
    single_cell = tf.contrib.rnn.GRUCell(size)
AttributeError: 'module' object has no attribute 'GRUCell'
```

Is it must to move to TensorFlow 0.12.1? or Is there any patch to resolve this issue?

**Comment by nealwu** [comment]
Hi @asispatra, yes this is expected to occur on 0.12.0. We recommend updating to a newer installation of TensorFlow -- either building from source or installing from nightly builds, as specified above.

**Comment by vincenttsai2015** [comment]
@nealwu I have updated to r0.12.1, but the attribute error still exists......How can I deal with this? Thanks.
![image](https://cloud.githubusercontent.com/assets/13366052/22583080/ae3318b8-ea25-11e6-9ed7-0eeb3797cb8c.png)

**Comment by nealwu** [comment]
@vincenttsai2015 I think you still aren't on the latest version of TensorFlow. As you can see from the [`__init__.py` file](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/rnn/__init__.py), `tf.contrib.rnn` definitely exports `GRUCell`. Try [installing from source](https://www.tensorflow.org/get_started/os_setup#installing_from_sources).

**Comment by Chejo-gt** [comment]
hello, I am using Ubuntu with ananconda and have the same issue, but when I tried to installing from source I obtain this error trying to executing the "./configure" scritpt:

...............
unexpected pipe read status: (error: 2): No such file or directory
Server presumed dead. Now printing '/home/cut_edge_technology/.cache/bazel/_bazel_cut_edge_technology/13ebb8ad2ebb0a0f86a2caa7ab0abb8f/server/jvm.out':
java.lang.ExceptionInInitializerError
        at java.lang.J9VMInternals.ensureError(J9VMInternals.java:141)
        at java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:130)
        at com.google.devtools.build.lib.skyframe.SkyframeExecutor.skyFunctions(SkyframeExecutor.java:351)
        at com.google.devtools.build.lib.skyframe.SkyframeExecutor.init(SkyframeExecutor.java:578)
        at com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutor.init(SequencedSkyframeExecutor.java:249)
        at com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutor.create(SequencedSkyframeExecutor.java:208)
        at com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutor.create(SequencedSkyframeExecutor.java:156)
        at com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutorFactory.create(SequencedSkyframeExecutorFactory.java:50)
        at com.google.devtools.build.lib.runtime.WorkspaceBuilder.build(WorkspaceBuilder.java:86)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.initWorkspace(BlazeRuntime.java:204)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.newRuntime(BlazeRuntime.java:1011)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.createBlazeRPCServer(BlazeRuntime.java:838)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.serverMain(BlazeRuntime.java:777)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:565)
        at com.google.devtools.build.lib.bazel.BazelMain.main(BazelMain.java:57)
Caused by: java.lang.ClassCastException: com.ibm.lang.management.UnixExtendedOperatingSystem incompatible with com.sun.management.OperatingSystemMXBean
        at com.google.devtools.build.lib.util.ResourceUsage.<clinit>(ResourceUsage.java:45)

**Comment by nealwu** [comment]
Hi @Chejo-gt, you no longer need to install from source to use `tf.contrib.rnn.GRUCell`. Installing from pip should do the job; see https://www.tensorflow.org/install/.
