### ISSUE TITLE
movinet tf2.1 : cannot import name 'image_preprocessing'

### ISSUE THREAD

**Issue by fangwudi** [tensorflow/models#9991]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ y] I am using the latest TensorFlow Model Garden release and TensorFlow 2.1
- [ y] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [ y] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/vision/beta/projects/movinet
@Hyperparticle 

## 2. Describe the bug

in movinet_tutorial.ipynb:
from official.vision.beta.configs import video_classification
error raised:

from tensorflow.python.keras.layers.preprocessing import image_preprocessing as image_ops
ImportError: cannot import name 'image_preprocessing'

## 3. Steps to reproduce

my env:
tensorboard              2.1.0
tensorflow-addons        0.9.1
tensorflow-datasets      4.0.0
tensorflow-estimator     2.1.0
tensorflow-gpu           2.1.0
tensorflow-hub           0.12.0
tensorflow-metadata      0.30.0
tensorflow models: git clone and then export PYTHONPATH

## 5. Additional context

Include any logs that would be helpful to diagnose the problem.

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):ubuntu 16.04
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary):pip
- TensorFlow version (use command below):2.1
- Python version:3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:10.1
- GPU model and memory:

**Comment by saikumarchalla** [comment]
@fangwudi  FYI - The error is not related to `from official.vision.beta.configs import video_classification`  module and  it is due to `from official.vision.beta.projects.movinet.configs import movinet as movinet_configs` module. Thanks!

**Comment by fangwudi** [comment]
I update tf to 2.3, and it's solved.

**Comment by saberkun** [comment]
Most of lastest code in the repo work with TF 2.4. The master branch is always developing with tf-nightly.

**Comment by riyaj8888** [comment]
why the prediction of movinet model  on kinetic dateset samples like 'arm wrestle ' is wrong .
during prediction it predicting only class num:129 .
i am following the inference code that is shared on repo README file. 
[https://github.com/tensorflow/models/tree/master/official/vision/beta/projects/movinet#prediction-examples](url)

**Comment by riyaj8888** [comment]
`import tensorflow as tf

from official.vision.beta.projects.movinet.modeling import movinet
from official.vision.beta.projects.movinet.modeling import movinet_model

# Create backbone and model.
backbone = movinet.Movinet(
    model_id='a0',
    causal=True,
    use_external_states=True,
)
model = movinet_model.MovinetClassifier(
    backbone, num_classes=600, output_states=True)

path =  '/home/ubuntu/EventRecognition/arm wrestle_low.mp4'
inp = load_video(path, max_frames=50, resize=(224, 224))
# Create your example input here.
# Refer to the paper for recommended input shapes.
inputs = tf.constant(inp.reshape(-1,50,224,224,3))

# [Optional] Build the model and load a pretrained checkpoint
model.build(inputs.shape)

checkpoint_dir = '/home/ubuntu/EventRecognition/movinet_a0_stream/'
checkpoint_path = tf.train.latest_checkpoint(checkpoint_dir)
checkpoint = tf.train.Checkpoint(model=model)
status = checkpoint.restore(checkpoint_path)
status.assert_existing_objects_matched()

# Split the video into individual frames.
# Note: we can also split into larger clips as well (e.g., 8-frame clips).
# Running on larger clips will slightly reduce latency overhead, but
# will consume more memory.
frames = tf.split(inputs, inputs.shape[1], axis=1)

# Initialize the dict of states. All state tensors are initially zeros.
init_states = model.init_states(tf.shape(inputs))

# Run the model prediction by looping over each frame.
states = init_states
predictions = []
for frame in frames:
  output, states = model({**states, 'image': frame})
  predictions.append(output)

# The video classification will simply be the last output of the model.
final_prediction = tf.argmax(predictions[-1], -1)
print("final_prediction",final_prediction)
# Alternatively, we can run the network on the entire input video.
# The output should be effectively the same
# (but it may differ a small amount due to floating point errors).
non_streaming_output, _ = model({**init_states, 'image': inputs})
non_streaming_prediction = tf.argmax(non_streaming_output, -1)
`
